### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#10]
@Gou-29 @hsun3163 @at-crx I'm starting this ticket to hash out some docker images I hope to build and use for the project

- [x] base-bioinfo: contains basic bioinformatics tools such as vcftools, bcftools, plink, tabix, and a basic python 3 environment. We need to version each software here. This can be based on `gaow/base-notebook` (?)
- [x] PEER: contains only PEER program
- [x] APEX: contains only APEX program
- [x] TensorQTL: contains only TensorQTL program
- [x] mash: for mashr and ebnm
- [x] susie: for susieR
- [x] polyfun: for polyfun
- [x] metal: for metal
- [x] flashpca: for flashpca, eg `RUN Rscript -e 'devtools::install_github("gabraham/flashpca/flashpcaR")'; RUN R --slave -e "library(flashpcaR)"`

**Comment by hsun3163** [comment]
Another docker image will be the one for normalization, which need pyqtl package and bx-python package

**Comment by hsun3163** [comment]
I will start building sigularity image that are listed here to minimize impact from enviorment

The built singularity image will all be stored in /mnt/mfs/statgen/xqtl_pipeline_sif/

**Comment by gaow** [comment]
@hsun3163 for testing the MWE it should be enough that we use docker images? I think it makes the most sense if I can see all the docker images being created. Could you move all the docker files to a folder called `docker` in the root of the repo, and name them `module.dockerfile` eg `PEER.dockerfile`?

**Comment by hsun3163** [comment]
> @hsun3163 for testing the MWE it should be enough that we use docker images? I think it makes the most sense if I can see all the docker images being created. Could you move all the docker files to a folder called `docker` in the root of the repo, and name them `module.dockerfile` eg `PEER.dockerfile`?

Me and @Gou-29 encountered some issues in accessing the normalization docker image that he built. So I found a tool online that can convert docker file to singularity recipe and built the sif on our cluster already, the container successfully run the required scripts, but with some hanging issues.

At the moment, all the dockerfile would be stored in the 
`/mnt/mfs/statgen/containers/xqtl_pipeline_sif/dockerfile/`
and their singularity counter part
`/mnt/mfs/statgen/containers/xqtl_pipeline_sif/singularity_file/` and named accordingly. I will make a copy of them in the docker folder of the repo.

**Comment by Gou-29** [comment]
@gaow: I have now finalized all the dockerfile for PEER and APEX. All previous issues have been eliminated. I think i may need to push it to somewhere then. I am now finalizing the documentation for them and will update today NY time

**Comment by gaow** [comment]
Thank you @Gou-29 you can push it to the docker folder @hsun3163 created under the root of the repo?

**Comment by hsun3163** [comment]
I am under the impression that mvsusie is dependent on mmbr, mashr, susieR, and other packages that are also used in mash, so should we merge them into 1 container?

**Comment by gaow** [comment]
Yes that is a good idea.

**Comment by gaow** [comment]
@at-crx could you double-check Ting's notes and complete `polyfun` docker or singularity configuration, and push to the repo under `container` folder? Please update to the latest version of the repo before you proceed.
