### ISSUE TITLE
Lack of "transcript_type" tags in gtf

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#100]
The collapse_annotation script from gtex produce following errors with the gtf we generated:
```
Traceback (most recent call last):
  File "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/collapse_annotation.py", line 294, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/collapse_annotation.py", line 89, in __init__
    attributes.pop('transcript_type'), g, start_pos, end_pos)
KeyError: 'transcript_type'
```
As it turns out, the gtf they are using have the transcript_type information, as shown below:
```
##description: evidence-based annotation of the human genome (GRCh38), version 26 (Ensembl 88)
##provider: GENCODE
##contact: gencode-help@sanger.ac.uk
##format: gtf
##date: 2017-03-14
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000223972.5"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; level 2; havana_gene "OTTHUMG00000000961.2";
chr1    HAVANA  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; **transcript_type "processed_transcript"**; transcript_name "DDX11L1-002"; level 2; transcript_support_level "1"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";
```

while ours dont have, as shown below:
```
chr1    havana  transcript      11869   14409   .       +       .       "transcript_id ""transcript:ENST00000456328""; gene_id ""gene:ENSG00000223972"""
chr1    havana  exon    11869   12227   .       +       .       "transcript_id ""transcript:ENST00000456328""; gene_id ""gene:ENSG00000223972"";"
```

The transcript_type info is not in the gff3 at the first place, as shown below:

```
1       havana  pseudogene      14404   29570   .       -       .       ID=gene:ENSG00000227232;Name=WASH7P;biotype=unprocessed_pseudogene;description=WASP family homolog 7%2C pseudogene [Source:HGNC Symbol%3BAcc:HGNC:38034];gene_id=ENSG00000227232;logic_name=havana_homo_sapiens;version=5
1       havana  pseudogenic_transcript  14404   29570   .       -       .       ID=transcript:ENST00000488147;Parent=gene:ENSG00000227232;Name=WASH7P-201;biotype=unprocessed_pseudogene;tag=basic;transcript_id=ENST00000488147;transcript_support_level=NA;version=1
1       havana  exon    14404   14501   .       -       .       Parent=transcript:ENST00000488147;Name=ENSE00001843071;constitutive=1;ensembl_end_phase=-1;ensembl_phase=-1;exon_id=ENSE00001843071;rank=11;version=1
```

_____________________________
The exact usage of the transcript_type information is yet to be investigated. If this info is not important, maybe we can artificially added them or changes to collapese_annotation.py script to avoid using it.

It seems that the transcript_type tag does nothing but retaining said information. I think we can get away with manually adding a string like "transcript_type : unknown" in the gtf file we generated
_____________________________________________
The reason for this error to occurs is that the GTEX pipeline cater specific to the genecode annotation format:
https://www.gencodegenes.org/pages/data_format.html

**Comment by gaow** [comment]
Does the `gtf` format file downloaded from links on #95 work? As discussed, we can use that file directly.

**Comment by hsun3163** [comment]
> Does the `gtf` format file downloaded from links on #95 work? As discussed, we can use that file directly.

That is a huge improvement, 
```
1       havana  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; tag "basic"; transcript_support_level "1";
```
As shown above,  transcript_biotype is exactly transcript_type, I could add a line in the gtf processing step to change it though.

**Comment by gaow** [comment]
@hsun3163 i would suggest that we use downloaded gtf directly, and modify collapese_annotation.py replacing transcript_type with transcript_biotype? We can achieve this in the docker config running eg:

```
RUN perl -pi -e 's/transcript_type/transcript_biotype/g' collapse_annotation.py
```

**Comment by hsun3163** [comment]
> @hsun3163 i would suggest that we use downloaded gtf directly, and modify collapese_annotation.py replacing transcript_type with transcript_biotype? We can achieve this in the docker config running eg:
> 
> ```
> RUN perl -pi -e 's/transcript_type/transcript_biotype/g' collapse_annotation.py
> ```

That could work too, but at the moment we will need to modify the gtf anyway to ensure the chromosome annotation are consistant between the fasta file and gtf file. so we are reading it in already

**Comment by gaow** [comment]
>  ensure the chromosome annotation are consistant between the fasta file and gtf file. 

Can you elaborate? We should not touch the original reference and we should not have to do that.

**Comment by hsun3163** [comment]
In our fasta file, the position of a gene is shown as:

```
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

Wherease in our GTF file, the position is shown as:
```
#!genome-build-accession NCBI:GCA_000001405.28
#!genebuild-last-updated 2020-08
1       havana  gene    11869   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene";
1       havana  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; tag "basic"; transcript_support_level "1";
1       havana  exon    11869   12227   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; exon_number "1"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; exon_id "ENSE00002234944"; exon_version "1"; tag "basic"; transcript_support_level "1";
```
As you can see, the format for the notation of chromosome is different. In order for both RSEM and STAR to work, they will need to be in the same format, i.e. both are 1 or both are chr1, but not both.

Therefore it is necessary to unify the files by either modifying the fasta or the gtf.

**Comment by gaow** [comment]
@hsun3163 please check the gft download website more carefully. I believe you can download a version with chr prefix for chr names. That is what we specified in the PDF standardized file guideline -- the one with chr.

**Comment by hsun3163** [comment]
A conclusion:
1. The gtf came without chr prefix
2. For STAR, there is an option to handle 1, as documented in the module
3. For RSEM, no such option is available 

Therefore, the gtf was processed, and used for downstream analysis.
