### ISSUE TITLE
What to do with the QCed bam in bulk expression

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#105]
At the moment, after step3, RNA_QCed BAM is not used for RSEM quantification,

as shown in the following image:
![image](https://user-images.githubusercontent.com/54919134/151224529-e2f3c9e2-648a-46b5-ac2e-92ea567c3957.png)

Therefore  in fact it has no impact in the downstream analysis.
So I wonder what to do with it?

One potential proposal is to feed the output from RNA_QCed to the RSEM quantification, but since the original workflow didnt do that, I don't know if doing so is incorrect.

**Comment by gaow** [comment]
It seems an error to me in the flowchart ... @Gou-29  could you verify and/or explain why RSEM does not use BAM file after QC?

**Comment by hsun3163** [comment]
As it turn out. the output of RNASeQC is not a bam file, but 
```
{sample}.gene_reads.gct : A tab-delimited GCT file with (Gene ID, Gene Name, coverage) tuples for all genes which had at least one read map to at least one of its exons
{sample}.gene_tpm.gct : A tab-delimited GCT file with (Gene ID, Gene Name, TPM) tuples for all genes reported in the gene_reads.gct file. Note: this file is renamed to .gene_rpkm.gct if the --rpkm flag is present.
```

It seems that the output of RSEM is better to serve as the input of downstream analysis, therefore I will try to add picardQC before RSEM.

**Comment by hsun3163** [comment]
The current implementation of picard didnt allow to sort by transcriptome, to changes it, at least we need to changes the python wrapper developed by gtex

**Comment by hsun3163** [comment]
It is even more complicated than my previouse comments: According to the document of the -ASO flag of picard, there doenst seems to be a obvious way to works with the Aligned to transcriptome bam file. 
```
If not null, assume that the input file has this order even if the header says otherwise. Default value: null. Possible values: {unsorted, queryname, coordinate, duplicate, unknown} Cannot be used in conjuction with option(s) ASSUME_SORTED (AS)
```

**Comment by hsun3163** [comment]
We decided not to qc the RSEM input for duplicates and use the output from RNA_QC  step as gene level counts for downstream analysis
