### ISSUE TITLE
Options for stranded vs unstranded analysis

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#109]
This ticket is to document the options that needs to be consistant in terms of stranded vs unstranded sequence method

stranded:
```
collapse_annotation: --collapse-only
RSEM : is_stranded: true 
run_rnaseqc: --stranded option
```

unstranded:
```
collapse_annotation:  remove "--collapse-only"
RSEM : is_stranded: false 
run_rnaseqc: {uncleared yet}
```

**Comment by gaow** [comment]
We need to explicitly code this into the workflow. We cannot document it here hoping someone will find and read it before writing their commands. I've attempted to integrate them to the workflow (to be committed)
