### ISSUE TITLE
Normalization module addition note

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#11]
The normalization module was added, taking care of the pink section of the following diagram
![Blank diagram](https://user-images.githubusercontent.com/54919134/147001732-cd7dbe78-6e88-44f8-a69c-8c191ec48405.png) 

### Input
The input for this workflow is:
1. 1 complete gene data table
2. 1 complete gene tmp table
3. 1 gtf table downloaded from genecode
4. 1 index file cross referencing the sample name in the expression and genotype

Requirement for input 1 and 2:
1. Sep by "\t"
2. have 2 unneeded rows above colname
3. file name end with gct
4. can only have samples in input 4
5. Must have same samples

Requirement for input 4
1. sample_id must not be all numeric,
2. Sep by "\t"

### Output
For each collection, the output is 1:
1. normalized Molecular_phenotype bed file

### Dependency:
import numpy as np
import pandas as pd
import gzip
import subprocess
import scipy.stats as stats
import argparse
import os
import qtl.io
import qtl.norm
from collections import defaultdict
from bx.intervals.intersection import IntervalTree

To get qtl and bx:
```
pip install pyqtl bx-python 
```
tabix (in bash)
bgzip (in bash)

Other common python packages are installed on the cluster already and probably installed in base-notebook already as well

Havent test but it should run relatively well due to its simplicity.

To test, run the following command
```
cd /mnt/mfs/statgen/xqtl_workflow_testing/module/normailzation
sos run /home/hs3163/GIT/xqtl-pipeline/pipeline/data_preprocessing/phenotype/normalization.ipynb Normalization  \
--counts_gct "./geneCounts.gct"         --tpm_gct "./geneTpm.gct"        \
--vcf_chr_list "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/vcf_chrom_list"     \
--sample_participant_lookup "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/sampleSheetAfterQc.txt"      \
--name "test"         --script_dir "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/" --wd ./       \
--annotation_gtf /mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/gencode.v26.annotation.gtf.gz  -s build &
```
The test result will be saved in nohup. The files used above were processed such that the requirement were met.

it should collapse the gtf, and then normalize the input data.
Potential issues: 
1. it may complained about vcf_chr_list , if so, please try adding all chrom (1 to 22) in the vcf_chrom_list file to see if it works
2. it may complained about vcf_chr_list , if so, please try switching the first and second columns names of sample_participant_lookup 

Please also noted other issues

@Gou-29

**Comment by hsun3163** [comment]
with the added containers and a customized input, the Normalization module can finally run without error message. But 1 issue remains: the output file contains no entries. This is likely due to some kind of filtering or matching that resulted in the removal of them.

@Gou-29 can you try to figure it out to see what happended?
```
cd /mnt/mfs/statgen/xqtl_workflow_testing/module/normailzation
sos run /home/hs3163/GIT/xqtl-pipeline/pipeline/data_preprocessing/phenotype/normalization.ipynb Normalization  \
--counts_gct "/mnt/mfs/statgen/xqtl_workflow_testing/module/normailzation/geneCounts.gct"         --tpm_gct "/mnt/mfs/statgen/xqtl_workflow_testing/module/normailzation/geneTpm.gct"        \
--vcf_chr_list "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/vcf_chrom_list"     \
--sample_participant_lookup "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/sampleSheetAfterQc.txt"      \
--name "demo"         --script_dir "/mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/" --wd ./       \
--annotation_gtf /mnt/mfs/statgen/xqtl_workflow_testing/expression_normalization/gencode.v26.annotation.gtf.gz \
--container /mnt/mfs/statgen/containers/xqtl_pipeline_sif/singularity_file/Normalization.sif &
```
The input outlined above is what I used to generate the error message free run

**Comment by Gou-29** [comment]
I will do it then. Do you think that error is from the python script instead? Also, I really have a hard time when getting access to the cluster. Is there any minimum example available (maybe in the source of code) for us to test that at least the codes in sos and docker are correct?

**Comment by hsun3163** [comment]
> I will do it then. Do you think that error is from the python script instead? Also, I really have a hard time when getting access to the cluster. Is there any minimum example available (maybe in the source of code) for us to test that at least the codes in sos and docker are correct? 

The thing is, we cannot change the code from py script...I will download the data to be used and send it to you.
