### ISSUE TITLE
sjdbOverhang in STAR index

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#113]
This parameter is documented in the pipeline as: 

* `sjdbOverhang`: specifies the length of the genomic sequence around the annotated junction to be used in constructing the splice junctions database. Ideally, this length should be equal to the ReadLength-1, where ReadLength is the length of the reads.

which is very clear. However there is a default value set to 150. Does it correspond to what's best to use for the current commonly used platforms?

**Comment by hsun3163** [comment]
I missed to changes it back to what TOPmed have, 100
but based on here:
https://groups.google.com/g/rna-star/c/h9oh10UlvhI/m/BfSPGivUHmsJ

It seems to be safer to set this value to be larger

**Comment by gaow** [comment]
Okay i set it to 100 to be consistent with topmed. Also added your link to Google group discussion above to the document
