### ISSUE TITLE
Problem with Normalization module (eqtl_prepare_expression.py)

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#124]
the eqtl_prepare_expression.py in fact read the data(gcts  and sample_sheet) in via wrapper of pandas. 

the sample_name in sample_sheet will be saved to index, while the sample_name(header of gct) will be save to columns

After the data was read, numpy will intersect the columns of gct and the index of sample_sheet.

When the sample_name is all numeric.

the columns of gct is still str (for whatever reason), but the index of the sample_sheet is interger (no way to save int as str in index it seems.) and thus create our problem.

In order to change it will minimum amount of codes

I change the command of 
```
    ix = np.intersect1d(counts_df.columns,vcf_lookup_s.index )

```

into

```
   ix = np.intersect1d(counts_df.columns, pd.Series([str(x) for x in vcf_lookup_s.index]))
```

which fix the numeric sample ID problem.

**Comment by gaow** [comment]
Good find. But I think when you read data in pandas you should be able to specify column data type and we can force it to be str not int? That upstream fix may be better

**Comment by hsun3163** [comment]
It was already force to str by default, but:
1. Index col was not force 
or
2. Index col cant take number as str

Either way, this upstream fix doesn't work

**Comment by gaow** [comment]
Current solution is to use Pandas 1.4.0+ and explicitly specify col types. We hacked it into the docker image replaced one line of code from the expression_processing script. We may later (or very soon!) submit a PR to the GTEx repo.
