### ISSUE TITLE
bcftools fill-tags remove all records in vcf

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#131]
Following command remove all the record and produce a sample file on our full data

```
nohup singularity exec bioinfo.sif bcftools +fill-tags /mnt/mfs/statgen/snuc_pseudo_bulk/data/genotype_data/test.leftnorm.vcf.gz.tmp_1.vcf.gz -t all,F_MISSING,'VD=sum(DP)' &
```
but 

```
nohup singularity exec bioinfo.sif bcftools +fill-tags /mnt/mfs/statgen/snuc_pseudo_bulk/data/genotype_data/test.leftnorm.vcf.gz.tmp_1.vcf.gz  &
```
retain the datas.

The file `/mnt/mfs/statgen/snuc_pseudo_bulk/data/genotype_data/test.leftnorm.vcf.gz.tmp_1.vcf.gz` was uploaded onto google drive and can be found here https://drive.google.com/file/d/1sSCjbMrJRx-coi_34_WbLH0rn56DhL9N/view?usp=sharing

**Comment by gaow** [comment]
> all the record and produce a sample file on our full data

You mean remove all variants and produce an empty file?

**Comment by gaow** [comment]
Unrelated and easy to do -- the file extensions obviously needs a fix to remove multiple vcf.gz in filename ...

**Comment by hsun3163** [comment]
yes I just found that, the -- is the reason for the removal.
So tmp_2 is fine already.
Will test the rest tomorrow.
