### ISSUE TITLE
Engineering problem for implementing parallelization for VCF_QC

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#145]
Goal: conduct vcf_qc per chrome

Features:
1.  VCF_QC should be able to handle 1 file vcf input and a list file of vcf input
2.  VCF_QC should be able to use vcf with chr name and without, vcf without chr name shall be preprocessed first

## Proposed mechanism 1:
```
[dbsnp_1, qc_1, rename_chr]
skip_if(rename_chr = False)

[qc_2, (variant preprocessing)]
input: f'{output_from("X") if rename_chr else genoFile}'
```
This design didnt work, give an error message as follow:
```
Invalid directive: SyntaxError('invalid syntax', ('<string>', 1, 10, 'def func(f\'{test_file if Skip = False else output_from("A")}\'\n'))
```

## Proposed mechanism 1.1:

similar to 1 put the if statement outside of input:

```
[A]
skip_if(skip)
input: test_file, group_by = 1
output: f'{_input}.mod'
bash: expand= "${ }"
    echo "modded" >> ${_output}

[B]
input: output_from("A") , group_with = "test_file"
input_file = _test_file if skip else _input 
bash: expand= "${ }"
    echo ${input_file}
```

Expected behavior:
When skip = True, B will works on each of the _test_file
When skip = False, B will works on each of the output from A

Actual behavior:
When skip = False. it works
When skip = True, following error occurs:
```
INFO: Running A:
INFO: Running B:
ERROR: [B]: [B]: Failed to process input statement output_from("A") , group_with = "test_file"
: Length of provided properties (2) does not match number of groups (1)
```
Which should be due to output_from A being empty

## Proposed mechanism 2:

Ditch the fancy mechanism, but do
```
[qc_add_chr_1, rename_chr]
...
[qc_add_chr_2, variant preprocessing_add_chr ]

[qc_1, variant preprocessing]

```

where [qc_1, variant preprocessing] and [qc_add_chr_2, variant preprocessing_add_chr ] is enssentially the same block of codes with only the input differs. Proposed mechanism 2 should definitly work for it is nothing new.

## Propose mechanism 3:
Use a wrapper to run vcf_qc, which also will definitly work but not fit into our overall design philosophy.

**Comment by hsun3163** [comment]
The ipynb I used to tested mechanism 1.1 is attached. Due to restriction of github it was gzipped
[test.ipynb.gz](https://github.com/cumc/xqtl-pipeline/files/8051449/test.ipynb.gz)

**Comment by gaow** [comment]
@hsun3163 We should use the [SoS auxiliary workflow feature](https://vatlab.github.io/sos-docs/doc/user_guide/outcome_oriented.html). See below:

```
[rename_chr: provides = '{filename}.renamed.vcf']
input: f'{filename}.vcf'
bash: expand = '${ }'
	touch ${_input:n}.renamed.vcf

[qc]
parameter: vcf_files = list
input: vcf_files, group_by = 1
output: f"{_input:n}.log"
bash: expand = True
	ls -lhrt {_input} > {_output}
```

save that as `test.sos` run the following:

```
touch chr1.vcf chr2.vcf
sos run test.sos qc --vcf-files chr1.vcf chr2.vcf
sos run test.sos qc --vcf-files chr1.renamed.vcf chr2.renamed.vcf
```

Hope it makes sense!

**Comment by hsun3163** [comment]
done
