### ISSUE TITLE
Duplicated variants in input VCF data

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#150]
While running project_samples, following error occurs:
```
Error: Input number of variants should be the same as used in the previous PCA model
Execution halted
```

The number of variante in unrelated sample is 18078403 
```
hs3163@node54:/mnt/mfs/statgen/snuc_pseudo_bulk$ wc /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.bim
 18078403 108470418 575387840 /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.bim
```

The number of variante in related sample is 18088235.

And it turns out, the --keep-variants file have 15871196  variants.

```
hs3163@node54:/mnt/mfs/statgen/snuc_pseudo_bulk$ wc /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.in
 15871196  15871196 206946773 /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.in
```
________________________________________________________________

The reason for this behavior occurs to be that plink fail to keep only the variants in the --extract file. After extract, the number of variants remains is clearly more than what is in the prune file, as indicated below:

In the related samples:
```
PLINK v1.90b6.18 64-bit (16 Jun 2020)
Options in effect:
  --bfile /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.related
  --extract /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.in
  --make-bed
  --memory 22500.0
  --mind 0.1
  --out /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.related.snuc_psudo_bluk.filtered.extracted
  --threads 20

Hostname: node56
Working directory: /mnt/mfs/statgen/snuc_pseudo_bulk
Start time: Sun Feb 13 20:10:50 2022

Random number seed: 1644801050
257630 MB RAM detected; reserving 22500 MB for main workspace.
44673996 variants loaded from .bim file.
1 person (0 males, 0 females, 1 ambiguous) loaded from .fam.
Ambiguous sex ID written to
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.related.snuc_psudo_bluk.filtered.extracted.nosex
.
--extract: 18088235 variants remaining.
Warning: At least 885183 duplicate IDs in --extract file.
0 people removed due to missing genotype data (--mind).
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 1 founder and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.99712.
18088235 variants and 1 person pass filters and QC.
Note: No phenotypes present.
--make-bed to
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.related.snuc_psudo_bluk.filtered.extracted.bed
+
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.related.snuc_psudo_bluk.filtered.extracted.bim
+
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.related.snuc_psudo_bluk.filtered.extracted.fam
... done.


```

In the unrelated samples:
```
hs3163@node54:/mnt/mfs/statgen/snuc_pseudo_bulk$ cat /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.log
PLINK v1.90b6.18 64-bit (16 Jun 2020)
Options in effect:
  --bfile /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered
  --extract /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.in
  --make-bed
  --memory 22500.0
  --out /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune
  --threads 20

Hostname: node66
Working directory: /mnt/mfs/statgen/snuc_pseudo_bulk
Start time: Sun Feb 13 19:53:56 2022

Random number seed: 1644800036
515677 MB RAM detected; reserving 22500 MB for main workspace.
44641185 variants loaded from .bim file.
423 people (0 males, 0 females, 423 ambiguous) loaded from .fam.
Ambiguous sex IDs written to
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.nosex
.
--extract: 18078403 variants remaining.
Warning: At least 885183 duplicate IDs in --extract file.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 423 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.996038.
18078403 variants and 423 people pass filters and QC.
Note: No phenotypes present.
--make-bed to
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.bed
+
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.bim
+
/mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.fam
... done.

End time: Sun Feb 13 19:58:58 2022

```

**Comment by gaow** [comment]
@hsun3163 looks like there is duplicated variant ID involved. This data is exported from VCF to PLINK. How did we handle variant ID there? We need to ensure the ID exported are unique eg using chr_pos_ref_alt. Could be a bit of challenge for indels when the sequence is very long ... but let's first make sure SNPs work.

**Comment by gaow** [comment]
@hsun3163 also `15871196` variants is way too much for PCA. Did you use MAF > 0.05 cutoff and do LD pruning on them?

**Comment by hsun3163** [comment]
> @hsun3163 looks like there is duplicated variant ID involved. This data is exported from VCF to PLINK. How did we handle variant ID there? We need to ensure the ID exported are unique eg using chr_pos_ref_alt. Could be a bit of challenge for indels when the sequence is very long ... but let's first make sure SNPs work.

So the ids are a mixture of rsID, which was introduced by the dbsnb reference, and chr:pos:alt:ref for the novel one.
```
hs3163@node54:/mnt/mfs/statgen/snuc_pseudo_bulk$ head /mnt/mfs/statgen/snuc_pseudo_bulk/Ast/genotype/GRCh38_liftedover_sorted_all.add_chr.leftnorm.filtered.snuc_psudo_bluk.unrelated.snuc_psudo_bluk.filtered.prune.in
rs199606420
chr1:10498:G:A
rs537182016
chr1:10543:G:A
```

**Comment by hsun3163** [comment]
> @hsun3163 also `15871196` variants is way too much for PCA. Did you use MAF > 0.05 cutoff and do LD pruning on them?

Oh just realized the default maf is 0, will do that again. But the problem of not eqaul amount of snps should not be caused by this though no?

**Comment by hsun3163** [comment]
This issue is caused by duplicated entries in the output of vcf_qc, two method was introduced to avoid it:
1. cancle left_norm in the vcf_qc
2. ensure chr:pos:alt:ref is the correct IDs

If the problem persist, one way to patch it is
run `sort {}.fam| cut -f 2 | uniq -d > dup_snp_list ` to get the duplicated snps.

And set the dup_snp_list as variants to be excluded in king (or explicitly remove them with a qc_no_prune step)

_______________________________________

Should we make detection of dup snp a default behavior in vcf_qc qc:3 though?

**Comment by gaow** [comment]
> If the problem persist, one way to patch it is

Do you setill see the problem? I think our proposal should fix it. If not we need to undersatnd why, and not simply delete them.

**Comment by hsun3163** [comment]
> > If the problem persist, one way to patch it is
> 
> Do you setill see the problem? I think our proposal should fix it. If not we need to undersatnd why, and not simply delete them.

The problem will persist if there is duplicated line in the input vcf already, just like our case.

**Comment by gaow** [comment]
Right, our VCF was preprocessed before with these artifacts introduced. 

Can we detect and report duplicate as part of the PLINK based QC? https://www.cog-genomics.org/plink/1.9/data#list_duplicate_vars.. We will add a step to remove these duplicates as the last step of `qc`?

**Comment by hsun3163** [comment]
> Right, our VCF was preprocessed before with these artifacts introduced.
> 
> Can we detect and report duplicate as part of the PLINK based QC? https://www.cog-genomics.org/plink/1.9/data#list_duplicate_vars.. We will add a step to remove these duplicates as the last step of `qc`?

The detection and removal of duplicates is better to be done as earlier as possible, before king. The best time to do it I think is right after vcf_qc_3. We can add one line in vcf_qc_3 to detect the dupes with sth like `sort {_output[0]:n}.fam | cut -f 2 | uniq -d > ${_output[1]}`  without another dedicated plink step.

**Comment by hsun3163** [comment]
An example for the duplication in our VCF is 
```
chr1:148483619:T:C      T       C       36590.6 PASS    AC=46;AF=0.0192953;AN=2384;BaseQRankSum=-0.938;DP=32922;ExcessHet=44.2595;FS=0.801;MLEAC=42;MLEAF=0.018;MQ=49.47;MQ0=0;MQRankSum=-0.049;QD=9.58;ReadPosRankSum=-0.071;SOR=0.8;VQSLOD=-4.67;culprit=MQ;F_MISSING=0.00334448;VD=32569;NS=1192;MAF=0.0192953;AC_Het=46;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=0.642352
chr1:148483619:T:C      T       C       5586.04 PASS    AC=15;AF=0.00628141;AN=2388;BaseQRankSum=-1.536;DP=33368;ExcessHet=6.0751;FS=2.571;MLEAC=15;MLEAF=0.006281;MQ=46.59;MQ0=0;MQRankSum=0.75;QD=7.02;ReadPosRankSum=0.553;SOR=0.405;VQSLOD=-6.823;culprit=MQ;F_MISSING=0.00167224;VD=33118;NS=1194;MAF=0.00628141;AC_Het=15;AC_Hom=0;AC_Hemi=0;HWE=1;ExcHet=0.956726
```

**Comment by hsun3163** [comment]
In the new vcf_qc module, no duplicates shall remain after qc_3 if remove_duplicated flag was added.
