### ISSUE TITLE
Provide QC summary and list of outlier samples / variants / genes without removing

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#159]
This was brought up in a recent discussion with GCAD members, that people may want to process samples and share them without dropping any. It would be desirable to implement a version of QC where we only list outlier samples / variants / genes without removing. 

This is not an immediate need since our end goal for now is not to serve a data resource. But something interesting to consider down the road.

**Comment by hsun3163** [comment]
For gwas_qc, this can be easily done by not removing those samples.
For phenotype, this would require a different version of readcount QC.
For vcf_qc I guess mark those failed qc as failed in their qc field then make an output for the failed entry?

**Comment by gaow** [comment]
Sorry i was referring to RNA-seq QC. I'll use #161 to follow up then post action items here

**Comment by gaow** [comment]
This is now implemented through the `multi_QC` program.
