### ISSUE TITLE
A sure way to know if task still running needed.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#163]
More often than not. Some of the task will run ~24Hr. There are three ways to know if the task is still running:
1. If the output file is updating (Good for module like vcf_qc that write their output gradually )
2. If the stdout file is updating (Good for module like PEER/susie etc. which give iteration progress)
3. Looks at nohup records see if it said still waiting for 1 task to complete
4. looks at qstat

However, sometimes these indicator give contradictory hints, as described in #162 , 2 stop updating abruptly after 15hrs, but 3 and 4 indicates that the task is still running. 

So I wonder, is there a sure way to find out?

**Comment by gaow** [comment]
@hsun3163 see here https://github.com/vatlab/sos/issues/1454 i think yoru `echo` is the best thing to do ... but if you notice I replaced it with simply `echo ${_output}`

**Comment by hsun3163** [comment]
> @hsun3163 see here [vatlab/sos#1454](https://github.com/vatlab/sos/issues/1454) i think yoru `echo` is the best thing to do ... but if you notice I replaced it with simply `echo ${_output}`

It is a bit different problem. The echo is to ensure the task is comptete after something is produce...whereas this is to see if the task is killed/stuck by whatever reason before waiting the whole walltimes...

**Comment by gaow** [comment]
this is not something a workflow tool (eg SoS) or job scheduler (eg PBS) can tell you.
