### ISSUE TITLE
default setting of chr name.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#178]
At the moment, the chr name of bed file is with a "chr" prefix, as a result of gtex's eqtl_expression_processing.py script, while the ones in the genotype without due to the conversion from vcf to plink, which by default changes the chr name back to numeric format.

This lead to an issue in the TensorQTL module, which require the two to be consistent.

A temporary patch to this issue is change the chr name in plink file while partitioning to get things work.

But we should make this decision upper stream and make things consistence btw genotype and phenotype.

As there seems no external references is needed in the downstream analysis. Either way of notation is fine.

One advantage of changing genotype instead of phenotype file is the ease of implementation and the speed: only adding 1 flag in plink and no noticeable increase in runtime.  While changing that of the bed file would be more time consuming for it will need a dedicate step to read every link in the bed file and then saved it to another file. 

However, it is also needed to verify whether plink will change the chr name from "chr*" to "*" even if the input is plink with "chr" in chr name.

**Comment by gaow** [comment]
@hsun3163 so you propose output chr to PLINK bim file? https://www.cog-genomics.org/plink/2.0/data#irreg_output 

I agree with that, if it works flawlessly under various scenarios you foresee.

**Comment by hsun3163** [comment]
For the time being, adding the chr prefix to plink shows no conflict. However, every time plink process a genotype file it will change the chr name back to number only. So the idea of setting this argument on the upstream doesnt work.
