### ISSUE TITLE
Output text sumstat result after PCA

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#183]
At the moment, the number of PCs to be used should be acquire from the cumulative plot of `pca.scree.png`

I understand that this is to let user make decision regarding the number of pcs to be used.

However, I wonder perhaps it would be more efficient to provides the sumstat that were used to build those plot as well? For example, for the `pca.scree.png`, we can output a table with 3 columns: PCs, PVE, and cumulative PVEs.

**Comment by gaow** [comment]
Sure, we should do it. Output to a .log file?

**Comment by hsun3163** [comment]
I will output it to a table so that it is easy to read and reproduce the plot. 
What I dont know is for the following clustering plot, whether/what should we output as sumstat result?
![Capture](https://user-images.githubusercontent.com/54919134/156653576-6e29c044-f587-4f83-b88d-a2d97ecb9fe9.JPG)

**Comment by gaow** [comment]
Maybe the multivariate mean and sd for each cluster?
