### ISSUE TITLE
fail to create vcf for snps with ref/alt not being ACTG

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#189]
The variant annotation package that we use to generate vcf file require the base character being strictly a combination of ACTG.

variants like `chr1:799081_G_*` will create a error message as follow:

```
Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0), : key 42 (char '*') not in lookup table
Traceback:
```

If those variates were skipped, then there is no problem.

**Comment by gaow** [comment]
> chr1:799081_G_* 

How does this happen?

**Comment by hsun3163** [comment]
That is because those * is in the orignal data set.
It was `chr1 799081 G GA,*`, then after vcf qc it became `chr1 799081 G GA` and `chr1 799081 G *`.

There are ~70 such instance among a gene with 2200 snps. I didnt count the others.

**Comment by gaow** [comment]
Thank you @hsun3163 for explaining. This is interesting to know ...
