### ISSUE TITLE
Docker file default CMD and entrypoint

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#195]
@hsun3163 when I write docker files, I typically end it with:

```
# Default command
CMD ["bash"]
```

but in your docker setup it's a lot more complicated eg 

```
RUN echo "cd /tmp" >> /entrypoint.sh
RUN echo "exec /bin/bash "$@"" >> /entrypoint.sh
RUN chmod u+x /entrypoint.sh
CMD /bin/bash /entrypoint.sh
```

why is this necessary?

**Comment by hsun3163** [comment]
This is originally from the dockerfile that I generated from singularity recipe via spython. As these look rather robust to me so I kept it in the downstream version of dockerfile. Aside from that there is no particular reason.
