### ISSUE TITLE
Add details about paired end reads to RNA-seq calling document

### ISSUE THREAD

**Issue by floutt** [cumc/xqtl-pipeline#203]
Hello!

So I was looking through the[ RNAseq calling document](https://cumc.github.io/xqtl-pipeline/code/molecular_phenotypes/bulk_expression.html) and noticed that there is no mention of the `--is_paired_end` option for RSEM in the documentation. This may result in errors for those using the pipeline with paired-end reads as the default is that the reads are not paired end. I think a note reminding people of the option would be useful.

Cheers,

Tosin

**Comment by floutt** [comment]
There is currently a setting for that in the program. By default it assumes single-end reads but you just have to set that parameter to change it to paired end (RSEM requires this as input). I think setting it as a required input (`--is-paired-end {bool}`) might be helpful.

**Comment by gaow** [comment]
It was done a while ago. @hsun3163 am cleaning up the issue reports. Please try to do the same on your end.
