### ISSUE TITLE
Proposal: A module for routine post association scan analysis

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#215]
Considering the memory/time-intensive nature of association scan. A sos module is needed to run some routine analysis on the cluster. Containing:

per-chr
1. Gene level fdr p.val adjustment 
2. Chr-wide n of sig association/snps
3. Top 1 snps for each gene and corresponding SNPs

Genome-wide
5. Genome level fdr pval adjustment for 3 
6.  Identify genome-wide n of sig  association/snps (simple sum of 2) + gene

Simple Colocalization:
7. Genes that are sig in all combinations of tissues

Output:
1. A table with:
1.1. Two-step adjusted p-value (1,4) for each gene
1.2. gene name and top snp named

________________________________________________________________
Q: shall we also extract the top/null/random signal here for the mixture prior

**Comment by gaow** [comment]
In principle this summary should be based on VCF format of output and use VCF utilities

**Comment by hsun3163** [comment]
There doesn't seem to be a built-in way to do multiple testing adjustments from bcftools though, which leads to this post.

I am envisioning the output of this module to be directly comparable to the gene level sumstat output from TensorQTL and APEX.

For the top/null/random signal, which needs z score, perhaps we could away with the bcftools -fill-tag to generate a customized tag.

**Comment by hsun3163** [comment]
Done
