### ISSUE TITLE
Check list for dependency update:

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#225]
This ticket serves as a reminder of the newly added software that required docker.

- [x] PEER (update PEER docker to include MOFA) (call it MOFA2 docker)
- [x] CUGG (Update cugg package with the updated function, then add cugg to bioinfo docker)
- [x] fastp as in #226 
- [x] SuSiE R update (Some connection error, pending resolve)
- [x] STAR updates to 10a

**Comment by hsun3163** [comment]
The error message for building the susie container is as followed:
```
+ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: keyserver receive failed: Connection timed out
```

**Comment by gaow** [comment]
this line makes it possible to add the cran R repo to Debian and therefore install R via apt-get. I dont see why we need it here in the stephenslab.dockerfile ... because you are not installing R here. Should be safe to remove.

**Comment by hsun3163** [comment]
Another problem with the susie container is installation of `devtools`, which seems to be problematic recently. After replacing it with `remotes` problem solved.

**Comment by gaow** [comment]
We have recently released a new version on cran for our SuSiE RSS manuscript (recent on PLoS Genetics) which is finally stablized after a coiuple of years work -- we can use cran release of SuSiE now.
