### ISSUE TITLE
trim_galore as an alternative adapter trimmer

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#226]
As discussed with others in the group, we should implement a module with trim_galore (wrapper to fastqc and cutadapt) as an alternative to trimmomatic -- the latter might work better but it requires user's input of adapter sequence file and in many cases analysts dont have the knowledge of what the adapter is (unless they are told of it by those who did the experiments). trim_galore on the other hand guesses what it is.  

Here are a couple of examples using trim_galore:

https://github.com/aryeelab/bisulfite-seq-tools/blob/d07254447a81639303cf1d98489a85d6d97ab5da/pipelines/bismark.wdl
https://gitlab.unimelb.edu.au/bshaban/metaGenePipe/-/blob/08851eceff5f4f182a088d367253eede82aa58a9/tasks/trim_galore.wdl

(I tried to find out if there is a way trimmomatic can guess the sequence but I didn't came across anything useful on that end. )

**Comment by hsun3163** [comment]
For reference, the way trim_galore guess reference is as followed:

```
Adapter auto-detection
If no sequence was supplied, Trim Galore will attempt to auto-detect the adapter which has been used. For this it will analyse the first 1 million sequences of the first specified file and attempt to find the first 12 or 13bp of the following standard adapters:

Illumina:   AGATCGGAAGAGC
Small RNA:  TGGAATTCTCGG
Nextera:    CTGTCTCTTATA

If no adapter contamination can be detected within the first 1 million sequences, or in case of a tie between several different adapters, Trim Galore defaults to --illumina, as long as the Illumina adapter sequence was one of the options. If there was a tie between the Nextera and small RNA adapter, the default is --nextera. The auto-detection results are shown on screen and printed to the trimming report for future reference. 
```

**Comment by hsun3163** [comment]
> the main advantage of trim_galore is to auto-detect adaptors, maybe we could add another tools to do this job then still use trimmomatic?
> There are two that were mentioned in https://www.biostars.org/p/364004/
> one of them, fastp , seems legit.

The current plan is to use fastp to auto-detect adaptor sequence and generate fasta file then use that for trimmomatic.
