### ISSUE TITLE
Example needed to QC VCF files after PCA

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#235]
On [this page](https://cumc.github.io/xqtl-pipeline/code/data_preprocessing/genotype_preprocessing.html#finalized-genotype-qc-as-a-result-of-pca) we have examples of PLINK final QC after PCA. We should add the same for VCF.

**Comment by hsun3163** [comment]
Not quite sure I followed. The vcf QC was done way upstream of the PCA result and was not used after.

**Comment by gaow** [comment]
I was referring to removing samples based on PCA results -- see [this section](https://cumc.github.io/xqtl-pipeline/code/data_preprocessing/genotype_preprocessing.html#finalized-genotype-qc-as-a-result-of-pca)

**Comment by gaow** [comment]
but maybe you can alternatively come up with the list of samples to analyze then we'll pass that list to downstreams analysis? We dont have to filter based on MAF beceause we can do that in tensorQTL.

**Comment by hsun3163** [comment]
It was proposed that we change the genotype qc section into a vcf-based process and use the vcf file in tensorQTL in PR #278. 

As discussed offline, this is undesirable unless genotype imputation became an issue.

Only when that is the case, an overhaul of genotype vcf shall be revisited.
