### ISSUE TITLE
Problems occured when using leafCutter

### ISSUE THREAD

**Issue by Rhopala** [cumc/xqtl-pipeline#247]
## Issue description
The main issue is we didn't get any clustered introns from MWE using the leafCutter differential splicing steps although the code ran and generated correct formated output files. And a mid-way problem is regtools whcih convert .bam files to junction files need user to specify input RNA strandness, however according to the regtool website (https://rnabio.org/module-09-appendix/0009/12/01/StrandSettings/) the STAR method we used just do not keep strandness info. But since I tried all three type of possible strandness and none of them would have clusters, the standness problem is not the cause.

## What's the expected result?

We cannot rule out the possibility that there is just no intron (or no cluster) in the MWE, so it is possible that no cluster is normal, but obviously we would like to see some cluster in the output.  

An output example in leafcutter website looks like this, each column corresponds to a different sample (original bam file) and each row to an intron, which are identified as chromosome:intron_start:intron_end:cluster_id.:

RNA.NA06986_CEU.chr1.bam RNA.NA06994_CEU.chr1.bam RNA.NA18486_YRI.chr1.bam RNA.NA06985_CEU.chr1.bam RNA.NA18487_YRI.chr1.bam RNA.NA06989_CEU.chr1.bam RNA.NA06984_CEU.chr1.bam RNA.NA18488_YRI.chr1.bam RNA.NA18489_YRI.chr1.bam RNA.NA18498_YRI.chr1.bam
chr1:17055:17233:clu_1 21 13 18 20 17 12 11 8 15 25
chr1:17055:17606:clu_1 4 11 12 7 2 0 5 2 4 4
chr1:17368:17606:clu_1 127 132 128 55 93 90 68 43 112 137
chr1:668593:668687:clu_2 3 11 1 3 4 4 8 1 5 16
chr1:668593:672093:clu_2 11 16 23 10 3 20 9 6 23 31

## What's the actual result?

In the output file there were only .bam file name headers but no clusters identified.

## Steps to reproduce the issue

The input I used was /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant/samp1.Aligned.sortedByCoord.out.bam.
If using that file alone, after installed everything as the steps in https://github.com/cumc/xqtl-pipeline/issues/252 localy:

1, create a directory with samp1.Aligned.sortedByCoord.out.bam.
2, In the terminal, run "samtools index samp1.Aligned.sortedByCoord.out.bam" (This is how leafCutter routine used to index the .bam file, however since our file is already indexed in previous steps so maybe we can skip it and just use the /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant/samp1.Aligned.sortedByCoord.out.bam.bai, no difference observed yet)
3, Run "regtools junctions extract -a 8 -m 50 -M 500000 -s 1 samp1.Aligned.sortedByCoord.out.bam -o samp1.Aligned.sortedByCoord.out.bam.junc" ("-s 0", "-s 2" gives the same result)
4, Run "echo samp1.Aligned.sortedByCoord.out.bam.junc >> test_juncfiles.txt"
5, Run "python leafcutter/clustering/leafcutter_cluster_regtools.py -j [the directory you placed the input]/test_juncfiles.txt -m 50 -o [whatever test name] -l 500000"
6, Open the output with "zcat [whatever test name]_perind_numers.counts.gz | more" and there should be no clusters

If working with multiple files loop step 2~4 on each file before running step 5

## What do I think is the problem?
First of all since we know little about what WME is for so possibly not having cluster is a correct result, for example if there is just no introns there will not be clusters. My guess on 5/13/2022 about there can not be overlap of intron splicing site inside the same .bam file could be wrong since there is no evidence showing one .bam file only contains one RNA-seq read.

And, inspired by Hao found two pakages were skiped in my installation in https://github.com/cumc/xqtl-pipeline/issues/252#issuecomment-1128287358. Not throwing error doesn't mean regtools or leafcutter script worked correctly.

## What did I do in my own attempt to fixing the issue?
1. When thinking that not having overlap is a problem I tried just copy and paste samp1.Aligned.sortedByCoord.out.bam to make multiple inputs, if there is any introns splicing in that file now there should be overlaps, however I still didn't get any clusters. According to how the leafCutter's paper described "intron cluster", it might be the case that exactly the same splicing event is not considered as one cluster, but I haven found verification from their code.

2. Seaking for other .bam files with appropriate size on our cluster to work around and see if I can get alternative outcome right now

----------------------------------------------------------Old Stuff-------------------------------------------------------------
The "regtools" (https://regtools.readthedocs.io/en/latest/) used by leafCutter somehow required to specify the RNA stranded status.
Cutted from terminal Message: 

[Program:        regtools
Version:        0.5.2
Usage:          regtools junctions extract [options] indexed_alignments.bam
Options:
                -s INT  Strand specificity of RNA library preparation
                         (0 = unstranded, 1 = first-strand/RF, 2, = second-strand/FR). REQUIRED
Please supply strand specificity with '-s' option!]

(And, all three flags were tried and all of them split the introns to zero clusters. Not sure if the problem is due to input .bam file or leafCutter code at current status.) <- 5/11/2022 stuff

5/13/2022 UPDATE: Figured out the reason why I wasn't getting any clusters is that the intron clusters are indentified through splicing site overlap across different .bam files. And I was applying the code to only one .bam file so of course there was no overlap. Trying it with multiplicated input now. 
P.S. Still working on identifying strand status

**Comment by hsun3163** [comment]
Based on https://github.com/alexdobin/STAR/issues/258 
The read is stranded when the gene count is stratified in one column.
The distribution of reads among genes is as follows:
where the first column is the number of genes, the second/third column is the reads in 3/4th columns in the gene read count table.

```
hs3163@node64:/mnt/mfs/statgen/xqtl_workflow_testing/rna_quant/output/rnaseq_test$ zcat sample_2.ReadsPerGene.out.tab.gz | cut -f 3,4|sort  | uniq -c
  53752 0       0
   1488 0       1
      1 0       11
      1 0       12
      1 0       15
      1 0       16
      1 0       18
    241 0       2
     56 0       3
      1 0       30
      1 0       31
     13 0       4
     11 0       5
      8 0       6
      1 0       62
      4 0       7
      1 0       75
      3 0       8
      2 0       9
    114 1       0
      6 1       1
      1 2       0
      1 3       0

```

**Comment by gaow** [comment]
For strandedness please check this https://cumc.github.io/xqtl-pipeline/code/molecular_phenotypes/calling/RNA_calling.html#strand-option there is a paper and a software to help you determine strand.

**Comment by gaow** [comment]
@Rhopala are you running the command on our MWE toy? If so, please document what you did in this ticket so people can reproduce it: https://cumc.github.io/gaow-wiki/orientation/github-issues.html#issues-for-bug-reports I can take a look or ask someone else (eg leafcutter authors) to take a look if I cannot figure it out.

**Comment by gaow** [comment]
@hsun3163 reassigned to you to show demo of my comment https://github.com/cumc/xqtl-pipeline/issues/247#issuecomment-1125357575 you can put it under [this section](https://cumc.github.io/xqtl-pipeline/code/molecular_phenotypes/calling/RNA_calling.html#strand-option) and also point to it from leafcutter module.

**Comment by Rhopala** [comment]
Just got chance to document it (with some current understanding) since this ticket is reopened.

**Comment by hsun3163** [comment]
The strands issue is fixed.
