### ISSUE TITLE
A worked leafcutter prerequisites installation routine:

### ISSUE THREAD

**Issue by Rhopala** [cumc/xqtl-pipeline#252]
【installation of regtools】
  $ git clone https://github.com/griffithlab/regtools
  $ cd regtools
  $ mkdir build
  $ cd build
  $ cmake ..
  $ make
(regtools is not working at this step, will be fixed later)

 【installation of samtools】
  $ cd ..
  $ wget https://github.com/samtools/samtools/releases/download/1.15.1/samtools-1.15.1.tar.bz2
  $  tar -xf samtools-1.15.1.tar.bz2
  $ cd samtools-1.15.1
  (Here is where things get tricky, I found I don’t have the access to usr/bin, which is the default installation location, so I needed to change the installation directory)
  $ ./configure --help 
 (will give related information, not necessary)
 $ ./configure --prefix=$HOME
 $ make
 $ make install
(This step created a bin directory under $HOME and installed samtools there)
  $ cd ..
  $ export PATH=$HOME/bin:$PATH
  (add the newly created bin directory to path)
  $ echo $PATH 
  (check if correctly added)
  $ cd regtools 
  (enter the regtools directory)
  $ mv regtools $HOME/bin 
  (move the regtools file (in color green) in the regtools directory to the bin path, after this step both samtools and regtools should be working)

【installation of leafcutter package】
  $ cd ..
  $ git clone https://github.com/davidaknowles/leafcutter

【installation of leafcutter related R packages】
  $ module load R/4.0
  $ R
(The following steps are in R, not sure all of them are necessary. These installations take some time. During R package installation there may be some question asking to select a CARN mirror, choosing any of them works.)
>Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1) # only necessary for Linux without the nodejs library / headers
>install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
>example(stan_model, package = "rstan", run.dontrun = TRUE) 
(the above step is just checking if the installation has succeed)
>if (!require("devtools")) install.packages("devtools", repos='http://cran.us.r-project.org')
>devtools::install_github("stan-dev/rstantools")
>devtools::install_github("davidaknowles/leafcutter/leafcutter")
>q()

**Till now all prerequisites of using leafcutter should be installed.**

Regtools reference page: https://regtools.readthedocs.io/en/latest/
Samtools reference page: https://github.com/samtools/samtools/blob/develop/INSTALL
Leaf cutter reference page: https://davidaknowles.github.io/leafcutter/
Rstan reference page: https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started

**Comment by hsun3163** [comment]
while installing the leafcutter into the singularity image, following error occurs
```
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Error: Failed to install 'leafcutter' from GitHub:
  (converted from warning) packages ‘Biobase’, ‘DirichletMultinomial’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Execution halted
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by gaow** [comment]
Looks like these use R version 3.15 ... perhaps we need to install R 3.15 to accommodate it -- just like what we did for the old PEER package.

**Comment by hsun3163** [comment]
They run in R 4.0 on our cluster so I was worrying something else may be causing the issue.

**Comment by gaow** [comment]
What packages are pulling `‘Biobase’, ‘DirichletMultinomial’` as dependencies? I looked at Bioconductor seems that  R 3.15 is the latest version these packages are supported.

**Comment by hsun3163** [comment]
Just the Leafcutter package

**Comment by hsun3163** [comment]
@Rhopala 
The buidling of singularity image is completed. The built image was stored as `/mnt/mfs/statgen/container/leafcutter.sif`. Can you: 
1. verify that the software installed in the image can be used properly,
2. try to build the `container/singularity/leafcutter.def` both for your learning purpose and to ensure reproducibility.
3. used the built leafcutter.sif to test the pipeline, and document what software is missed from it.

**Comment by Rhopala** [comment]
@hsun3163 
While verifying software installed in leafcutter.sif, found regtools not working.

1. if using the shell command it goes:
         $singularity shell xqtl_project/containers/leafcutter.sif
         Singularity> regtools --help
         bash: regtools: command not found

2. if using the exec command it goes:
         $ singularity exec xqtl_project/containers/leafcutter.sif regtools --help
         FATAL:   "regtools": executable file not found in $PATH

By constrast, samtools worked fine and after I created junction files in my own terminal, the following steps worked as expected in the container, therefore only regtools seems to be a problem.

**Comment by hsun3163** [comment]
Based on 
```
26735813-  173 |         JunctionsExtractor(string bam1, string region1, int strandness1, string strand_tag1, uint32_t min_anchor_length1, uint32_t min_intron_length1, uint32_t max_intron_length1) :
26736003-      |         ^~~~~~~~~~~~~~~~~~
26736038-In file included from /opt/regtools/src/variants/variants_annotator.h:35,
26736112-                 from /opt/regtools/tests/lib/variants/test_variants_annotator.cc:26:
26736198-/opt/regtools/src/junctions/junctions_annotator.h: In constructor ‘JunctionsAnnotator::JunctionsAnnotator(std::string)’:
26736323-/opt/regtools/src/junctions/junctions_annotator.h:194:16: warning: ‘JunctionsAnnotator::output_file_’ will be initialized after [-Wreorder]
26736467-  194 |         string output_file_;
26736504-      |                ^~~~~~~~~~~~
26736540-/opt/regtools/src/junctions/junctions_annotator.h:184:17: warning:   ‘BedFile JunctionsAnnotator::junctions_’ [-Wreorder]
26736666-  184 |         BedFile junctions_;
26736702-      |                 ^~~~~~~~~~
26736737-/opt/regtools/src/junctions/junctions_annotator.h:220:9: warning:   when initialized here [-Wreorder]
26736839-  220 |         JunctionsAnnotator(string bedFile)
26736890-      |         ^~~~~~~~~~~~~~~~~~
26736925-[100%] Linking CXX executable TestVariants
26736968-[100%] Built target TestVariants
26737001-+ cd /opt
```

The compilation of regtools should be successful. However, the `regtools` bin doesn't exist after the compilation, investigation  pending.

**Comment by hsun3163** [comment]
The cause of this issue is simply that regtools binary locates within the `regtools/build` dir,  instead of the `regtools` dir
