### ISSUE TITLE
Process to remove :a in the pipeline.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#263]
To improve the portability of the pipeline, absolute path are to be removed from each of the modules that will produce a recipe file.

At the moment, the module containing ":a" are as follows:
Whether each of them is needed shall be reviewed. 

```
hs3163@node54:~/GIT/xqtl-pipeline/pipeline$ grep :a * | cut -d \"  -f 1 | uniq -dc
```

- [ ]      10 APEX.ipynb:
- [ ]       2 BiCV_factor.ipynb:
- [ ]       3 GRM.ipynb:
- [ ]       5 METAL.ipynb:
- [ ]       2 PCA.ipynb:
- [ ]       3 PEER_factor.ipynb:
- [ ]       4 RNA_calling.ipynb:
- [ ]       5 SuSiE.ipynb:
- [ ]       8 SuSiE_RSS.ipynb:
- [ ]       8 TensorQTL.ipynb:
- [ ]       3 VCF_QC.ipynb:
- [ ]       5 bulk_expression_QC.ipynb:
- [ ]      29 bulk_expression_commands.ipynb:
- [ ]       3 covariate_formatting.ipynb:
- [ ]      41 eQTL_analysis_archive.ipynb:
- [ ]      26 eQTL_analysis_commands.ipynb:
- [ ]       5 fastqtl_to_mash.ipynb:
- [ ]      11 gene_annotation.ipynb:
- [ ]       8 genotype_formatting.ipynb:
- [ ]       4 gwas_enrichment.ipynb:
- [ ]      13 mashr.ipynb:
- [ ]       2 mixture_prior.ipynb:
- [ ]       4 mvenloc.ipynb:
- [ ]       9 polyfun.ipynb:
- [ ]       2 rds_to_vcf.ipynb:
- [ ]       4 reference_data.ipynb:
- [ ]       5 sample_matcher.ipynb:
- [ ]      10 summary_stats_merger.ipynb:
- [ ]       6 sumstat_processing.ipynb:
- [ ]       3 yml_generator.ipynb:

**Comment by hsun3163** [comment]
From my perspective, the absolute path is good for usage within our cluster and tracking the file footprint. But it will require the user to run the command generator and each step before it on their cluster/computer before entering any single step. So maybe it is time to change it.

**Comment by gaow** [comment]
@hsun3163 is this to accommodate the needs for command generator? We purposely use absolute path eg `{cwd:a}` all over the place to ensure all files are tracked in place and they are not meant to be transferred, although people can always run -s build if they move the files around. So I dont see that as a limitaiont. Some (old) programs dont even take relative paths ... (I ran into this multiple times in my career although less and less in the recent years) so it's save to use :a. 

But I get your point. And that's actually not contradictory to using :a in the pipeline because the commands themselves do not have to be in absolute paths! You have this problem  because of your design -- you need explicit `output` (and `input`) to based ur command generator . You now see this is one immediate draw back of your design #262 . I think we can improve #262 to solve this and not bother with changing it in all pipelines.

**Comment by hsun3163** [comment]
> @hsun3163 is this to accommodate the needs for command generator? We purposely use absolute path eg `{cwd:a}` all over the place to ensure all files are tracked in place and they are not meant to be transferred, although people can always run -s build if they move the files around. So I dont see that as a limitaiont. Some (old) programs dont even take relative paths ... (I ran into this multiple times in my career although less and less in the recent years) so it's safe to use :a.
> 
> But I get your point. And that's actually not contradictory to using :a in the pipeline because the commands themselves do not have to be in absolute paths! You have this problem because of your design -- you need explicit `output` (and `input`) to based ur command generator . You now see this is one immediate draw back of your design #262 . I think we can improve #262 to solve this and not bother with changing it in all pipelines.

It is actually to accommodate the needs of this
```
[Gao](https://app.slack.com/team/UPTTGKPCM)  [3 days ago](https://statgenworkspace.slack.com/archives/D0169CE21C4/p1652817626331239?thread_ts=1652816021.287019&cid=D0169CE21C4)
We should best include all the files generated anyways on Google drive so people can grab the data to test any steps
```
Otherwise I am in fact a big fan of using :a

**Comment by hsun3163** [comment]
> @hsun3163 is this to accommodate the needs for command generator? We purposely use absolute path eg `{cwd:a}` all over the place to ensure all files are tracked in place and they are not meant to be transferred, although people can always run -s build if they move the files around. So I dont see that as a limitaiont. Some (old) programs dont even take relative paths ... (I ran into this multiple times in my career although less and less in the recent years) so it's safe to use :a.

Based on this, it is unwise to remove the `:a`, will recline this ticket
