### ISSUE TITLE
Unsorted output from STAR.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#266]
As it turns out, bam generated using the command on leafcutter with STAR in our sif is Align.out.bam ( Code shown in the next post).

 Corresponding to the `--outSamType bam unsorted` option. However, this result is quite puzzling because, according to run_star.py,  `--outSamType bam unsorted` is exactly the option it used, as shown below:
```
parser.add_argument('--quantMode', default=['TranscriptomeSAM', 'GeneCounts'], nargs='+', help='Outputs read counts, and a BAM with reads in transcriptome coordinates')
parser.add_argument('--outSAMtype', default=['BAM', 'Unsorted'], nargs='+')
parser.add_argument('--outSAMunmapped', default='Within', help='Keep unmapped reads in output BAM')
parser.add_argument('--outSAMattrRGline', default=['ID:rg1', 'SM:sm1'], nargs='+', help='Adds read group line to BAM header; required by GATK')
parser.add_argument('--outSAMattributes', default=['NH', 'HI', 'AS', 'nM', 'NM', 'ch'], nargs='+')
parser.add_argument('--varVCFfile', default=None, help='VCF for the input sample; currently supports SNPs only')
parser.add_argument('--waspOutputMode', default='SAMtag')
parser.add_argument('--chimSegmentMin', default='15', help='Minimum chimeric segment length; switches on detection of chimeric (fusion) alignments')
parser.add_argument('--chimJunctionOverhangMin', default='15', help='Minimum overhang for a chimeric junction')
parser.add_argument('--chimOutType', default=['Junctions', 'WithinBAM', 'SoftClip'], nargs='+', help='')
parser.add_argument('--chimMainSegmentMultNmax', default='1', help='')
parser.add_argument('--chimOutJunctionFormat', default='0', help='Formatting for Chimeric.out.junction')
parser.add_argument('--genomeLoad', default='NoSharedMemory')
parser.add_argument('--sjdbFileChrStartEnd', default=None, help='SJ.out.tab file (e.g., from 1st pass). With this option, only one pass will be run')
parser.add_argument('--STARlong', action='store_true', help='Use STARlong instead of STAR')
parser.add_argument('-t', '--threads', default='4', help='Number of threads')
args = parser.parse_args()

if args.STARlong:
    starcmd = 'STARlong'
else:
    starcmd = 'STAR'

# set up command
cmd = f'{starcmd} --runMode alignReads --runThreadN {args.threads} --genomeDir {args.index}'
if args.annotation_gtf is not None:  # only needed if genome index was built w/o annotation
    cmd += f' --sjdbGTFfile {args.annotation_gtf}'
if args.sjdbFileChrStartEnd is None:
    cmd += ' --twopassMode Basic'
cmd += f' --outFilterMultimapNmax {args.outFilterMultimapNmax}'\
    + f' --alignSJoverhangMin {args.alignSJoverhangMin}'\
    + f' --alignSJDBoverhangMin {args.alignSJDBoverhangMin}'\
    + f' --outFilterMismatchNmax {args.outFilterMismatchNmax}'\
    + f' --outFilterMismatchNoverLmax {args.outFilterMismatchNoverLmax}'\
    + f' --alignIntronMin {args.alignIntronMin}'\
    + f' --alignIntronMax {args.alignIntronMax}'\
    + f' --alignMatesGapMax {args.alignMatesGapMax}'\
    + f' --outFilterType {args.outFilterType}'\
    + f' --outFilterScoreMinOverLread {args.outFilterScoreMinOverLread}'\
    + f' --outFilterMatchNmin {args.outFilterMatchNmin}'\
    + f' --outFilterMatchNminOverLread {args.outFilterMatchNminOverLread}'\
    + f' --limitSjdbInsertNsj {args.limitSjdbInsertNsj}'\
    + f" --readFilesIn {' '.join(args.fastq)}"
if args.fastq[0].endswith('.gz'):
    cmd += ' --readFilesCommand zcat'
cmd += f' --outFileNamePrefix {os.path.join(args.output_dir, args.prefix)}.'\
    + f' --outSAMstrandField {args.outSAMstrandField}'\
    + f' --outFilterIntronMotifs {args.outFilterIntronMotifs}'\
    + f' --alignSoftClipAtReferenceEnds {args.alignSoftClipAtReferenceEnds}'\
    + f" --quantMode {' '.join(args.quantMode)}"\
    + f" --outSAMtype {' '.join(args.outSAMtype)}"\
    + f' --outSAMunmapped {args.outSAMunmapped}'\
    + f' --genomeLoad {args.genomeLoad}'
```

So supposedly, an unsorted version of bam should be produced by our STAR module as well, which run_STAR did not. My guess is one of the many STAR option overwrite the `outSamType` option.

**Comment by Rhopala** [comment]
$ singularity shell xqtl_project/containers/rna_quantification.sif
Singularity> STAR --genomeDir /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_2/STAR_Index --readFilesIn /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r1.fq.gz /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r2.fq.gz --twopassMode Basic --outSAMstrandField intronMotif --readFilesCommand zcat --outSAMtype BAM Unsorted

The output of that are: Aligned.out.bam, Log.final.out,  Log.out,  Log.progress.out,  SJ.out.tab,  _STARgenome, _STARpass1

When using "samtools index Aligned.out.bam", Error occured: 
[E::hts_idx_push] Chromosome blocks not continuous
[E::sam_index] Read 'A00477:17:HFTFJDMXX:2:2203:7310:5228' with ref_name='5', ref_length=181538259, flags=99, pos=115830921 cannot be indexed
samtools index: failed to create index for "Aligned.out.bam": No such file or directory

Similar error happened with /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant/samp1.Aligned.toTranscriptome.out.bam:
[E::hts_idx_push] Chromosome blocks not continuous
[E::sam_index] Read 'A00477:17:HFTFJDMXX:1:1488:14705:37012' with ref_name='transcript:ENST00000490232', ref_length=300, flags=419, pos=10 cannot be indexed
samtools index: failed to create index for "samp1.Aligned.toTranscriptome.out.bam": No such file or directory

samtools were able to index /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant/output/rnaseq/samp1.Aligned.sortedByCoord.out.bam

**Comment by hsun3163** [comment]
Because samtool can only sort the bam that is sorted by coordinates. Generation of unsorted bam and further investigation of this issue is likely not needed.

**Comment by gaow** [comment]
@hsun3163 what if you run:

```
Singularity> STAR --genomeDir /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_2/STAR_Index --readFilesIn /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r1.fq.gz /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r2.fq.gz --twopassMode Basic --outSAMstrandField intronMotif --readFilesCommand zcat --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM GeneCounts
```

adding `--quantMode` must be where the difference is.

**Comment by gaow** [comment]
@Rhopala my guess is we should use `Aligned.sortedByCoord.out.bam` but let's ask the developers. 

> Because samtool can only sort the bam that is sorted by coordinates. Generation of unsorted bam and further investigation of this issue is likely not needed.

@hsun3163 i dont understand this sentence. But you can imagine taking unsorted bam and sort that with samtools first, then create index. Because these are not documented on the leafcutter website we better ask to confirm.

**Comment by Rhopala** [comment]
> 

Ok running this I've got Both "Aligned.out.bam" and "Aligned.toTranscriptome.out.bam", still none could be indexed by samtools.

**Comment by Rhopala** [comment]
> @hsun3163 what if you run:
> 
> ```
> Singularity> STAR --genomeDir /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_2/STAR_Index --readFilesIn /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r1.fq.gz /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r2.fq.gz --twopassMode Basic --outSAMstrandField intronMotif --readFilesCommand zcat --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM GeneCounts
> ```
> 
> adding `--quantMode` must be where the difference is.

Ok running this I've got Both "Aligned.out.bam" and "Aligned.toTranscriptome.out.bam", still none could be indexed by samtools.

**Comment by gaow** [comment]
> Ok running this I've got Both "Aligned.out.bam" and "Aligned.toTranscriptome.out.bam"

I wonder what's preventing it from giving you `Aligned.sortedByCoord.out.bam`?

**Comment by Rhopala** [comment]
> > Ok running this I've got Both "Aligned.out.bam" and "Aligned.toTranscriptome.out.bam"
> 
> I wonder what's preventing it from giving you `Aligned.sortedByCoord.out.bam`?

My logs:

```
        STAR --genomeDir /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_2/STAR_Index --readFilesIn /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r1.fq.gz /mnt/mfs/statgen/xqtl_workflow_testing/rna_quant_hans/data/samp1_r2.fq.gz --twopassMode Basic --outSAMstrandField intronMotif --readFilesCommand zcat --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM GeneCounts
        STAR version: 2.7.10a   compiled: 2022-01-14T18:50:00-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
May 25 10:54:25 ..... started STAR run
May 25 10:54:25 ..... loading genome
May 25 10:55:27 ..... started 1st pass mapping
May 25 10:55:29 ..... finished 1st pass mapping
May 25 10:55:30 ..... inserting junctions into the genome indices
May 25 10:56:42 ..... started mapping
May 25 10:56:45 ..... finished mapping
May 25 10:56:46 ..... finished successfully
Singularity> ls
Aligned.out.bam                  Log.final.out  Log.progress.out      SJ.out.tab   _STARpass1
Aligned.toTranscriptome.out.bam  Log.out        ReadsPerGene.out.tab  _STARgenome
```
Doesn't seem like there are any error in it. @hsun3163 is that look the same as what you've done when forming the Aligned.sortedByCoord.out.bam file?

**Comment by gaow** [comment]
it should not be too hard to figure it out by taking parameters in effect off the STAR command generated by our pipeline until you find which parameter(s) changed the behavior.

**Comment by Rhopala** [comment]
OK I think I got what happend, --outSamType bam unsorted is not overwritten within the STAR command options. The reason why our pipeline got Aligned.sortedByCoord.out.bam output is because there were some postprocessing in the [run_star.py](https://github.com/broadinstitute/gtex-pipeline/blob/master/rnaseq/src/run_STAR.py) . Similar to us, they got "Aligned.out.bam" and "Aligned.toTranscriptome.out.bam" file from star and after that they just sorted the "Aligned.out.bam" via samtools and name it with the extension "Aligned.sortedByCoord.out.bam" (and deleted the original "Aligned.out.bam" output). Therefore although "Aligned.sortedByCoord.out.bam" is a STAR default extension, the "Aligned.sortedByCoord.out.bam" file we got was not a direct output of STAR.

Somewhere around line 130 in run_star.py:

```
# postprocessing

    ...

    # sort BAM (use samtools to get around the memory gluttony of STAR)
    print(f'[{datetime.now().strftime("%b %d %H:%M:%S")}] Sorting BAM', flush=True)
    cmd = f'samtools sort --threads {args.threads} -o {args.prefix}.Aligned.sortedByCoord.out.bam {args.prefix}.Aligned.out.bam'
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
    os.remove(f'{args.prefix}.Aligned.out.bam')
    print(f'[{datetime.now().strftime("%b %d %H:%M:%S")}] Finished sorting BAM', flush=True)

    # index BAM
    print(f'[{datetime.now().strftime("%b %d %H:%M:%S")}] Indexing BAM', flush=True)
    cmd = f'samtools index {args.prefix}.Aligned.sortedByCoord.out.bam'
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
    print(f'[{datetime.now().strftime("%b %d %H:%M:%S")}] Finished indexing BAM', flush=True)

   ...
```

**Comment by gaow** [comment]
That's a bit embarrassing that we had that ticket posted but it is fine.
You can edit the ticket to simply ask if we should sort it before samtool
index. That's still the missing part in their documentation

On the go. Sorry for short text.
