### ISSUE TITLE
psichomics container file

### ISSUE THREAD

**Issue by ryanyord** [cumc/xqtl-pipeline#279]
The documentation for psichomics splicing calling appears to have some mention: [splicing_calling.ipynb](https://github.com/cumc/xqtl-pipeline/blob/main/code/molecular_phenotypes/calling/splicing_calling.ipynb). 

Could a container file for psichomics be created?

**Comment by hsun3163** [comment]
Hi ryanyord, thank you for your interest! The part for psichomics is still under development and we are unable to provide a container for psichomics yet.

**Comment by hsun3163** [comment]
It is done.
