### ISSUE TITLE
Remove cugg import in sumstat_to_vcf_1 (summary_stats_merger.ipynb)

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#285]
This step imports ss_2_vcf from cugg.sumstat, but then defines the ss_2_vcf function which negates the need for the import. Also, the regular pip installation of cugg doesn't seem to come with the ss_2_vcf function so the job fails due to the import.

**Comment by hsun3163** [comment]
Hi Travyse, thank you for bringing this up. In the most recent PR, we have finalized the ss_2_vcf .etc function and added the cugg package to the bioinfo container.
