### ISSUE TITLE
When standardizing sumstat, how to ID an association with GENE:Transcripts:SNPs?

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#297]
At the moment, for each norminal pvalue, we have the following information:

`molecular_trait_object_id `
`molecular_trait_id `(ID of the molecular trait used for QTL mapping. Depending on the quantification method used, this can be either a gene id, exon id, transcript id or a txrevise promoter, splicing or 3'end event id. Examples: ENST00000356937, ENSG00000008128.

and SNP :`chromosome `_`position `_`ref `_`alt `

Is it that in all scenario, `molecular_trait_id` is map to 1 and only 1 unique `molecular_trait_object_id` ? 

if that is not the case, then we will need to use molecular_trait_object_id:molecular_trait_id:SNP as the unique identifier for each entry.

**Comment by gaow** [comment]
> Is it that in all scenario, molecular_trait_id is map to 1 and only 1 unique molecular_trait_object_id

Yes

**Comment by hsun3163** [comment]
In this case, `molecular_trait_id_chromosome_position_ref_alt` will be used.
