### ISSUE TITLE
Some gene ID in psichomics not in our GTF

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#308]
In the psichomics example output some genes, for example SEPT6 , doesn't present in our GTF and hence prevent us from setting the correct TSS for those genes.
```
bed_df.query("gene_name not in @test_output.gene_name.unique() ")
```

| #Chr | start | end | ID | 10518782 | 11395417 | 20214850 | gene_name
|-- | -- | -- | -- | -- | -- | -- | -- | --
chr1 | 1060393 | 1065830 | SE_1_+_1060393_1063079_1063201_1065830_RP11-54... | 0.682927 | 0.884615 | 0.625000 | RP11-54O7.18
chr1 | 1600706 | 1606873 | SE_1_+_1600706_1602073_1605362_1606873_Hypothe... | 0.615385 | 0.183673 | 0.399529 | Hypothetical
chr1 | 1739704 | 1745724 | SE_1_-_1745724_1744668_1744251_1739704_SLC35E2 | 0.945946 | 0.587302 | 1.000000 | SLC35E2
chr1 | 3060283 | 3061107 | SE_1_-_3061107_3060604_3060501_3060283_LINC00982 | 0.634241 | 0.630332 | 0.405941 | LINC00982
chr1 | 3061331 | 3062290 | SE_1_-_3062290_3061813_3061591_3061331_LINC00982 | 0.753846 | 0.745455 | 0.800000 | LINC00982
| ... | ... | ... | ... | ... | ... | ... | ...
chrX | 19935898 | 19937505 | A5SS_X_-_19937505_19937418_19935898_CXorf23 | 0.045455 | 0.200000 | 0.122727 | CXorf23
chrX | 119637195 | 119640715 | A5SS_X_-_119640715_119640692_119637195_SEPT6 | 1.000000 | 1.000000 | 0.977778 | SEPT6
chrX | 119650098 | 119652859 | A5SS_X_-_119652859_119652854_119650098_SEPT6 | 1.000000 | 0.990000 | 0.980392 | SEPT6
chrX | 149937480 | 149938193 | A5SS_X_-_149938193_149938142_149937480_CXorf40B | 0.130435 | 0.125000 | 0.093750 | CXorf40B
chrX | 153320757 | 153321552 | A5SS_X_-_153321552_153321502_153320757_LL0XNC0... | 0.000000 | 0.044444 | 0.022222 | LL0XNC01-16G2.1

**Comment by hsun3163** [comment]
Another issue is that, again, the gtf contains duplicates gene name for each gene ID, therefore we will not be able to uniquely map them. 

At the moment, the implementation is to 1. remove all the entries with duplicates gene ID in gtf, 2 remove all the entries without a gene ID in gtf.

**Comment by gaow** [comment]
>gtf contains duplicates gene name for each gene ID
Are the ensembl ID also duplicate? We need to work with ensembl ID.

**Comment by hsun3163** [comment]
After modifying the psichomics module, we will have ensemble ID instead of gene name in our psichomics result.
