### ISSUE TITLE
Error in fastqc: Analysis not complete

### ISSUE THREAD

**Issue by Shrishtee-kandoi** [cumc/xqtl-pipeline#320]
unzip:  cannot find or open /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/fastqc_dorso/02_120405.1, /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/fastqc_dorso/02_120405.1.zip or /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/fastqc_dorso/02_120405.1.ZIP.

When running the fastqc analysis, I see that it is looking for file with `{name}.zip` and the pipeline by default gives out `{name}_fastqc.zip` as in the picture which is why it is not being able to complete the analysis.

<img width="312" alt="Screen Shot 2022-07-13 at 11 54 29 AM" src="https://user-images.githubusercontent.com/98359418/178777735-3ed6a332-7661-419d-bdf2-5db61cafc9d2.png">

**Comment by Shrishtee-kandoi** [comment]
Hi @hsun3163, Thank you so much ! I'll try running it again.

**Comment by hsun3163** [comment]
Fixed
