### ISSUE TITLE
while building container, wget download files to cluster instead of containers

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#333]
Following codes in the stephenlab.def
```
wget https://github.com/gabraham/plink2R/archive/${P2R_VERSION}.zip && \
unzip ${P2R_VERSION}.zip && \
```

downloads and unzip the file in ls /tmp, as shown below:
```
hs3163@csglogin:/tmp$ ls *zip*
d74be015e8f54d662b96c6c2a52a614746f9030d.zip  d74be015e8f54d662b96c6c2a52a614746f9030d.zip.1  d74be015e8f54d662b96c6c2a52a614746f9030d.zip.2  plink_linux_x86_64_20200616.zip
```

which creates the following issue and prevents the plink2R package from installation.
```
hs3163@csglogin:/mnt/vast/hpc/csg/containers$ cat nohup.out  | grep plink2R
+ wget https://github.com/gabraham/plink2R/archive/d74be015e8f54d662b96c6c2a52a614746f9030d.zip
--2022-07-27 16:54:54--  https://github.com/gabraham/plink2R/archive/d74be015e8f54d662b96c6c2a52a614746f9030d.zip
Location: https://codeload.github.com/gabraham/plink2R/zip/d74be015e8f54d662b96c6c2a52a614746f9030d [following]
--2022-07-27 16:54:54--  https://codeload.github.com/gabraham/plink2R/zip/d74be015e8f54d662b96c6c2a52a614746f9030d
replace plink2R-d74be015e8f54d662b96c6c2a52a614746f9030d/.gitignore? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
```

**Comment by gaow** [comment]
I think singularity would download to the physical disk -- it's not a problem with wget or docker. Perhaps we should add a force remove on the existing files prior to downloading them. eg `rm -rf /tmp/plink2R*`? Or tehre are other options in singularity to prevent this from happening in the first place?

**Comment by hsun3163** [comment]
I don't think singularity will download it to the /opt folder of physical disk, hence why I haven't notice this problem before. 

It is no exactly it has duplicate downloaded file, it is it has a existing unzipped folder and ask if we want to overwrite some read-only file within them, there should also be a way to force it to overwrite.

I have both remove the /tmp file and change the dir to /opt. Shall see how things go. If the problem indeed disappears then we are fine.

**Comment by hsun3163** [comment]
problem indeed disappears
