### ISSUE TITLE
Problem installing nloptr, a dependency for sesame

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#347]
While installing nloptr using r version 4.1.3 (as dependency requirement for sesame is R>=4.10) and the newest biocmanager version, following error occurs:

```
/mnt/mfs/cluster/bin/R-4.1.3/etc/Makeconf:177: recipe for target 'test-C-API.o' failed
make: *** [test-C-API.o] Error 1
ERROR: compilation failed for package 'nloptr'
* removing '/mnt/mfs/hgrcgrid/homes/hs3163/R/x86_64-pc-linux-gnu-library/4.1/nloptr'

The downloaded source packages are in
        '/tmp/RtmpYeEpIC/downloaded_packages'
Installation paths not writeable, unable to update packages
  path: /mnt/mfs/cluster/bin/R-4.1.3/library
  packages:
    MASS, Matrix, cluster, mgcv, nlme, survival
Warning message:
In install.packages(...) :
  installation of package 'nloptr' had non-zero exit status
```

with one error happened before:

```
mv: cannot move 'nlopt/lib' to a subdirectory of itself, 'nlopt/lib/lib'
configure: creating ./config.status
config.status: creating src/Makevars
```

and various error during the invocation of `test-C-API.o`:
```
In file included from /mnt/mfs/hgrcgrid/homes/hs3163/R/x86_64-pc-linux-gnu-library/4.1/testthat/include/testthat/testthat.h:65:0,
                 from /mnt/mfs/hgrcgrid/homes/hs3163/R/x86_64-pc-linux-gnu-library/4.1/testthat/include/testthat.h:1,
                 from test-C-API.cpp:12:
test-C-API.cpp: In function 'void ____C_A_T_C_H____T_E_S_T____0()':
test-C-API.cpp:107:35: error: call of overloaded 'abs(__gnu_cxx::__alloc_traits<std::allocator<double> >::value_type)' is ambiguous
     expect_true(abs(res[0] - 1./ 3) < 1.0e-4);
                                   ^
test-C-API.cpp:107:5: note: in expansion of macro 'expect_true'
     expect_true(abs(res[0] - 1./ 3) < 1.0e-4);
```

**Comment by hsun3163** [comment]
someone seems to be able to hack it by modifying the C++ source code. But given my non-existence knowledge of C++ and compilation, I would prefer some other solution.
https://www.mail-archive.com/r-devel@r-project.org/msg44105.html

**Comment by gaow** [comment]
this may have to do with c++ compiler not R versions .. perhaps a different version of gcc will work and this should be modifiable in Debian/Ubuntu systems quite easily if you search for alternative gcc compile Ubuntu.

**Comment by hsun3163** [comment]
> this may have to do with c++ compiler not R versions .. perhaps a different version of gcc will work and this should be modifiable in Debian/Ubuntu systems quite easily if you search for alternative gcc compile Ubuntu.

In another post regarding this error, people also claim that this is due to an error in the original C++ code, std::abs should be use instead of simple abs:
https://github.com/microsoft/onnxruntime/issues/3605

**Comment by hsun3163** [comment]
OK, as it turns out, while installing sesame from scratch, there is no need to install nloptr, therefore this ticket is closed.
