### ISSUE TITLE
Incorrect Range in summary_stats_standardizer.ipynb

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#351]
In TARGET_generation_2, we use an annotation file (${cwd}/chr_name) to rename chromosomes in our input file. When generating that annotation file, we use range(1,22):
`pd.DataFrame({"A" : list(range(1,22)) + ["X","Y","MT"],"X" : [ f'chr{x}' for x in  list(range(1,22)) + ["X","Y","MT"]]}).to_csv(f'{cwd}/chr_name',"\t",header = None, index = None )`

This will only account for chromosomes 1 - 21. So we just need to extend this range by 1 and use range(1,23), or else an error will occur while running TARGET_generation_2.
`pd.DataFrame({"A" : list(range(1,23)) + ["X","Y","MT"],"X" : [ f'chr{x}' for x in  list(range(1,23)) + ["X","Y","MT"]]}).to_csv(f'{cwd}/chr_name',"\t",header = None, index = None )`

**Comment by hsun3163** [comment]
Thank you, those are fixed and will be pushed in the new PR
