### ISSUE TITLE
Cugg Import Issues and Syntax Error (summary_stats_standardizer.ipynb)

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#352]
Multiple concerns surrounding Cugg:

1. We import ss_2_vcf from Cugg, then we also define that same function in TARGET_generation_1. We should either import or use the internally defined function, rather than doing both.
2. The bioinfo container uses pip to install Cugg, but the pip version of Cugg doesn't contain the ss_2_vcf function. So running TARGET_generation_1 fails.
3. If we comment out the import of the ss_2_vcf function from cugg.sumstats, things progress until I run into an error regarding this line in cugg.sumstats:
`if "GENE" in sumstats.columns.values():`
- We should remove the parenthesis when looking at the values of sumstats.columns. It should instead be:
`if "GENE" in sumstats.columns.values:`

I worked around this by forking cumc/cugg, fixing point 3, and commenting out the import of ss_2_vcf from cugg.

**Comment by hsun3163** [comment]
Hi Travyse, thank you for pointing this out, indeed the CUGG online is not the most up to date version, will let you know once the cugg and the containers is updated.

**Comment by hsun3163** [comment]
CUGG updated
