### ISSUE TITLE
"Bad Value" in CollectRnaSeqMetrics (RNA_calling.ipynb)

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#363]
We set the strand parameter in the `sample fastq list` file as fr, rf, missing_strand, or unstranded. However, the `CollectRnaSeqMetrics` module in `rnaseqc_call_1, rsem_call_1, picard_qc` requires the values to be NONE,  FIRST_READ_TRANSCRIPTION_STRAND, or SECOND_READ_TRANSCRIPTION_STRAND as seen below. Creating a dictionary with the pipeline strand values as the key, and the expected CollectRnaSeqMetrics values as the value would be a quick fix:

example: `{ 'unstranded': "NONE", 'fr': "FIRST_READ_TRANSCRIPTION_STRAND", ...}`

`Argument STRAND_SPECIFICITY has a bad value: unstranded. 'unstranded' is not a valid value for StrandSpecificity. Allowed values are Possible values: {NONE, FIRST_READ_TRANSCRIPTION_STRAND, SECOND_READ_TRANSCRIPTION_STRAND}`

**Comment by hsun3163** [comment]
Hi Travyse, thank you for pointing it out, this is exactly what we did in our latest patch. Would you mind pull the latest commit and try again?

**Comment by Travyse** [comment]
Ah, sorry about that! Thanks

**Comment by Travyse** [comment]
Done
