### ISSUE TITLE
devtools dependency fail in the new build of container.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#365]
In the new build of methylation_both container, the devtools was failed to be installed. Therefore a new implementation to use biocManager to install packages from GITHUB was used.

**Comment by gaow** [comment]
why `devtools` fails to install? You can also use `remotes::install_github()`

**Comment by hsun3163** [comment]
> why `devtools` fails to install? You can also use `remotes::install_github()`

It has to do with some dependency issues up to the package system_font. But since I used BiocManager to install most of the packages, including the sesame from GitHub, in this container, I think my current way should simplify things

**Comment by hsun3163** [comment]
New implementation works
