### ISSUE TITLE
Error in readPicard.rna_metrics (rnaseqc_call_5, RNA_calling.ipynb)

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#367]
When running the below code, we don't find any files so the job is prematurely stopped. I think the issue is that we're missing the `.gz` prefix for `.rna_metrics.gz`.

```
      if (isDir) {
        files <- system(paste("find -L", source, "-name \"*.rna_metrics\""), intern=TRUE)
        stopifnot(length(files) > 0)
        samples <- gsub(".rna_metrics", "", basename(files), fixed=TRUE)
      } else {
        files <- source
        samples <- gsub(".rna_metrics", "", basename(files), fixed=TRUE)
      }
```

**Comment by hsun3163** [comment]
Thank you for pointing it out, indeed I added the gz to the file produced by picard in the recent release to reflect its identity but didn't realized this problem. Surfix added.

**Comment by hsun3163** [comment]
Fix
