### ISSUE TITLE
NAs in methylation file

### ISSUE THREAD

**Issue by yuqimiao** [cumc/xqtl-pipeline#377]
Hi,

Below is shows the number of probes having NA: 
`hs3163@node60:/mnt/vast/hpc/csg/xqtl_workflow_testing/methyl/sesame_2$ cat ROSMAP_arrayMethylation_covariates.sesame.methyl.M.tsv | grep NA | wc
  59294 44589088 728822152
hs3163@node60:/mnt/vast/hpc/csg/xqtl_workflow_testing/methyl/sesame_2$ cat ROSMAP_arrayMethylation_covariates.sesame.methyl.beta.tsv | grep NA | wc
  59294 44589088 739016357
hs3163@node60:/mnt/vast/hpc/csg/xqtl_workflow_testing/methyl/sesame_2$`

How should we deal with the NAs in the methylation data?

file path: /mnt/vast/hpc/csg/xqtl_workflow_testing/methyl/sesame_2/ROSMAP_arrayMethylation_covariates.sesame.methyl.M.bed.gz

**Comment by hsun3163** [comment]
In the sesame package, the goto way of handling poor quality probes is by turning the unreliable values into NA. I have removed all the probes whose values for all samples are NAs. However,  as our pipeline for calculating residual Y at the moment do not allow NA in the Y matrix (.lm.fit in R ), I wonder what should be the general guidance to handle them.

**Comment by gaow** [comment]
1. Filter by 5% (ideally) or if 5% removes too much then try 10% filter? We remove probes with missing rates about this threshold.
2. AFter that we can use mean imputation or SoftImpute (R package)?

**Comment by hsun3163** [comment]
```
> 421618 - 396,583
Error: unexpected ',' in "421618 - 396,"
> 421618 - 396583
[1] 25035
>  tbl_filtered = filter_mtx(mtx%>%t(),0.1)%>%t()%>%as_tibble(rownames = colnames(bed)[4] )
> nrow(bed) - nrow(tbl_filtered)
[1] 19256
```
For 0.05, 25035 probes were removed. For 0.1, 19256 probes were removed.

For 0.05 treshold it is

**Comment by hsun3163** [comment]
Implemented as a optional module for any bed
