### ISSUE TITLE
sos -s build removing majority of the step output after using zapped.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#378]
After implementing the zapped file system. While @Shrishtee was trying to rerun the command for #373  using -s build, half of the `out.md.bam` output from picard_qc was removed.

The number of files can be outlined in the following tables
|file type | # Before rerun (expected #) |  # After rerun (expected #) | tracked by sos ? |
| --- | --- | ----| --- | 
|    .out.md.bam (Mark duplicated bam, output from picard ) |  209 (249) | 83 (249) | Yes | 
|    .out.bam|  2 (3) | 2 (3) | Yes (zapped)  |
|    .out.bam.zapped |  249 (249) | 251 (249) | created by sos |
|    rna_metrics.pdf (pdf version of rna qc, final picard commands tracked by sos )  | 252 (249) |  252 (249) | No  |
|    rna_metrics.gz  (raw version of rna qc, final picard commands, tracked by sos ) | Not checked |  83 (249) |   Yes |

@Shrishtee-kandoi Please correct me if I am wrong and provide more details, anything could be helpful. In particular:
1. The command for the rerun
2. The log file for this incident as attachment

**Comment by Shrishtee-kandoi** [comment]
`rnaseqc_call `script used for re-analysis:

```
#!/bin/bash -l

#$ -l h_rt=100:00:00 
#$ -N rnaseqc_call_batch2.sh 
#$ -j y
#$ -P casa


sos run  /restricted/projectnb/casa/xqtl-pipeline/pipeline/RNA_calling.ipynb rnaseqc_call \
    --cwd /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/rnaseqc_call/batch_2 \
    --samples /restricted/projectnb/casa/oaolayin/ROSMAP_batch_all/dlpfc_batch2.list \
    --data-dir /restricted/projectnb/casa/oaolayin/ROSMAP_batch_all/ \
    --fasta_with_adapters_etc TruSeq3-PE.fa  \
    --STAR-index /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/reference_data/STAR_Index/ \
    --gtf /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/reference_data/Homo_sapiens.GRCh38.103.chr.reformatted.collapse_only.gene.ERCC.gtf \
    --container /restricted/projectnb/casa/xqtl-pipeline/container/singularity/rna_quantification.sif \
    --reference-fasta /restricted/projectnb/casa/skandoi/reference_data/GRCh38_full_analysis_set_plus_decoy_hla.noALT_noHLA_noDecoy_ERCC.fasta \
    --walltime 100h \
    --numThreads 20 \
    --ref-flat /restricted/projectnb/casa/skandoi/ROSMAP_DLPFC/reference_data/Homo_sapiens.GRCh38.103.chr.reformated.ERCC.gtf.ref.flat \
    --mem 100G -J 50 -c csg.yml -q neurology -s build
```
Commit number: `commit f6349345be299175678095c56682403a501bbc76`

The log file for this incident is attached below:

[rnaseqc_call_batch2.sh.o7020351.txt](https://github.com/cumc/xqtl-pipeline/files/9507963/rnaseqc_call_batch2.sh.o7020351.txt)

**Comment by hsun3163** [comment]
There are couple things being strange:
1. There are 249 zapped file, but all out.bam were removed.
2. There are 249 zapped file, but only 209 out.md.bam files
3. There are 249 zapped file, but only 252 rna_metric.pdf files

**Comment by hsun3163** [comment]
Following sos script
```
```
produce following behavior:

```

hs3163@node65:/mnt/vast/hpc/csg/xqtl_workflow_testing/finalizing$ sos run test.sos --A t00209b9fcaf94929.err
INFO: Running test_1:
INFO: test_1 (index=0) is ignored due to saved signature
INFO: test_1 output:   t00209b9fcaf94929.err.B
INFO: Running test_2:
cat: t00209b9fcaf94929.err.B.C: No such file or directory
INFO: test_2 is completed.
INFO: test_2 output:   t00209b9fcaf94929.err.B.D
INFO: Workflow test (ID=wc5dfe40f34e990f4) is executed successfully with 1 completed step and 1 ignored step.
hs3163@node65:/mnt/vast/hpc/csg/xqtl_workflow_testing/finalizing$ sos run test.sos --A t00209b9fcaf94929.err -s build
INFO: Running test_1:
INFO: Step test_1 (index=0) is ignored with signature constructed
INFO: test_1 output:   t00209b9fcaf94929.err.B
INFO: Running test_2:
INFO: Step test_2 (index=0) is ignored with signature constructed
INFO: test_2 output:   t00209b9fcaf94929.err.B.D
INFO: Workflow test (ID=wc5dfe40f34e990f4) is ignored with 2 ignored steps.
```

Even though there is this error `cat: t00209b9fcaf94929.err.B.C: No such file or directory`, the zapped file is still produced. Which  is the root cause of the problem outlined here

**Comment by hsun3163** [comment]
By changing the script into, with a set -e command at the beginning:
```
[test_1]
parameter: A = path
input: A
output: f'{_input}.B'
bash: expand = "${ }"
        set -e
        touch ${_input}.B

[test_2]
output: f'{_input}.D'
bash: expand = "${ }"
        set -e
        cat  ${_input}.C
        cat  ${_input} > ${_input}.D

_input.zap()
```
The program quit properly.
