### ISSUE TITLE
Edit refactored modules

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#4]
As discussed earlier, the new organization of modules can be visualized at: https://cumc.github.io/xqtl-pipeline/ the toctree on the left side of the page. Each bold text is a **part**; each foldable line of text under the bold parts are **recipes** for a **xQTL specific analysis** task involving multiple modules; each folded line is a **module** that should be very generic, potentially applicable to xQTL and/or GWAS and/or other analysis.

## How does each component work?

1. We have several parts. These parts should correspond to the workflow schema plot on the landing page of the website
2. Each part has several recipes. These are meant to only contain `sos run` command lines  interactively with enough text explanations., with all parameters explicitly written out. This kind of notebooks should be of a tutorial nature.  In principle, *these notebooks can be `bash` notebooks*. People who wants to customize their analysis should refer to documentation and commands here.
3. Continuing 2, a particular example of complete recipe should be the ones under `Complete pipelines` part -- call it **master recipe** Those notebooks will each generate a bunch of `sos` commands to run the default analysis, putting together various recipe in 2 above. This notebook does not need much of an explanation but rather focusing on generating the proper `sos` commandlines. Readers should see 2 for more details about each recipe (which may contain one or multiple sos commands).
4. Notice that 2 and 3 should cover 95% user case -- that people dont have to read beyond **Recipes**. For the generic modules, the core implementation are in SoS but users dont have to read these modules except for learning purpose. For those few who want to edit the module notebooks we consider them developers or at least power users.

## Improving the modules

@Gou-29 

- [x] Data preprocessing --> Covariate data preprocessing --> Factor analysis using PEER
- [x] Data preprocessing --> Covariate data preprocessing --> Factor analysis using Bi-Cross validation
- [x] Data preprocessing --> Phenotype data preprocssing --> Molecular phenotype normalization (@hsun3163  shoud provide the first draft. Please include the GTEx reference repo link so @Gou-29 can double check and improve)
- [x] Data preprocessing --> Covariate data preprocessing --> Computing covariate residuals (@Gou-29 remember we have talked about adjusting this in both X and Y data. Let's stick to Y data for the time being because this seems an accepted convention by many people. We will implement alternatives down the road that includes X preprocessing).

Since you only have a few modules please proceed with improved documentation and MWE after you are done with the main code editing / testing.

@at-crx 

- [x] Statistical Fine-mapping --> Univariate fine-mapping --> polyfun pipeline (you need to create it)
- [x] Multivariate Integration --> Colocalization --> fastenloc (you need to create it)
- [ ] Multivariate Integration --> Colocalization --> susie-coloc (you need to create it)

@hsun3163 the rest. But be aware of previously written modules (discussed in person about what to do for them): 

- PCA
- GWAS QC
- the entire MASH section
- SuSiE_RSS

Also, there are a few notebooks in some folders that does not make into the table of contents on the website. Those are what we believe should eliminate after editing them into other modules.

**Important: for each module you edit, please open a github issue with input and output described in that issue -- I will review and discuss if those are appropriate input/output.**

## Update the recipes with new modules

@hsun3163 and @at-crx

**Comment by hsun3163** [comment]
- [ ] Data preprocessing --> Genotype --> GWAS_QC
- [ ] Data preprocessing --> Genotype --> LD
- [ ] Data preprocessing --> Genotype --> genotype_reformat
- [ ] Data preprocessing --> Genotype --> GRM
- [ ] Data preprocessing --> Phenotype--> Annotation
- [ ] Data preprocessing --> Phenotype--> Reformat
- [ ] Data preprocessing --> Phenotype--> Residual Y
- [ ] Data preprocessing --> Factor--> Merge of factor

- [ ] Association scan --> APEX--> APEX_cis
- [ ] Association scan --> TensorQTL--> TensorQTL_cis
- [ ] Association scan --> APEX--> APEX_trans
- [ ] Association scan --> TensorQTL--> TensorQTL_trans
- [ ] Meta analysis --> METAL 
- [ ] Meta analysis --> MASH
- [ ] Fine mapping --> SuSiE & MVSuSIE RSS

**Comment by gaow** [comment]
>  Data preprocessing --> Phenotype--> Residual Y

@hsun3163 this was assigned to @Gou-29 though. @Gou-29 please double check and unify with what @hsun3163 has edited in Residual_Y, before removing it.

**Comment by hsun3163** [comment]
> > Data preprocessing --> Phenotype--> Residual Y
> 
> @hsun3163 this was assigned to @Gou-29 though. @Gou-29 please double check and unify with what @hsun3163 has edited in Residual_Y, before removing it.

@Gou-29 please extract from my part of the code such that:
1. The handle the differences between samples in factor and samples in phenotype
1.1 at the moment the intersect was used, an alternative is to accommodate the situation where samples in phenotype is a subset of the factor file. To reduce the needs of modifing the input back and forth (the intersect section)

2. The output should have '#chr' ,start, end and gene_ID as the first four column. 
3. The output needs to be converted in to bed file and tabix (enssentially the bash part)

**Comment by Gou-29** [comment]
@hsun3163 Got it. Currently, 2 is satisfied. For 3, I believe it will be fairly easy. 

With regarding to 1, I think we can use samples in both files, and report any discrepancy in two of them.
