### ISSUE TITLE
Consistency on split (phenotype/genotype) by chromosome

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#413]
Split genotype by chromosome produces a list file with an #id column of just chromosome number (1,2,3,4...), while split phenotype by chromosome produces a list file with an #id column of chr# (chr1, chr2,...). In later steps (like cisQTL scan), there's an error on combining the two files at the #id column because of this discrepancy.

**Comment by hsun3163** [comment]
Got it. Thanks for pointing it out, it is a result of a recent change of partition for genotype I believe, am working on it.
