### ISSUE TITLE
sumstat_standarization remove nominal data way too aggressively 

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#416]
Shown below are the number of rows in the tensor_qtl's nominal_association long table before and after the sumstat standarizer process. 

```
 | Study        | Before sumstat_standarizer | After sumstat_standarizer | 
|--------------|----------------------------|---------------------------|
| snuc         | 10017096                   | 8561063                   | 
| STARNET-Run1 | 15769288                   | 13619962                  | 
| STARNET-Run2 | 15136973                   | 49000                     | 
| Methylation  | 30656248                   | 333819                    | 
```

As it turns out, after a certain commit (yet to find out), the sumstat_standardizer remove variants too aggressively.

____________________________

A potential remedy is to revert the standardizer to a previous commit (less generalizability) and run it ourselves

**Comment by hsun3163** [comment]
One of the potential reason could be that:

For snuc:
```
hs3163@csglogin:/mnt/vast/hpc/csg/snuc_pseudo_bulk/eight_celltypes_analysis$ wc reference_data/TARGET_ref_chr1.txt
  8597478  42987390 227866582 reference_data/TARGET_ref_chr1.txt
```
For methylation:
```
hs3163@node77:/mnt/vast/hpc/csg/molecular_phenotype_calling/TensorQTL_arch$ wc methyl_QTL.1.1.TARGET.ref
  822253  3289012 16079312 methyl_QTL.1.1.TARGET.ref
```

**Comment by hsun3163** [comment]
The number of snps in the genotype file is
872070

Therefore it actually make sense to have the less rows.

The one in the old version is all the gene-snp pairs

**Comment by hsun3163** [comment]
The problem comes with 
```
nq,_ = snps_match(query,subject,keep_ambiguous)
```

where 
```
Total rows of query:  6347906 Total rows of subject:  6344358
```
were reduced to
```
58649 rows × 15 columns
```

**Comment by hsun3163** [comment]
The source of the problem is that, compare_snp depends on the order of both the query and subject to be the same. Frankly, I am still confused by its mechanism and design. I may redo it with a `panda.merge()` based mechanism but not at this point.

Another smaller issue discovered is that there is an error in the documentation of the allele_match function that leads to a mistake mechanism that will not recognize allele_filp but discard them as non-match. 

At this point, the sumstat_standardizer will be change to accommodate these issue so that all other sumstat can processed asap

**Comment by gaow** [comment]
> compare_snp depends on the order of both the query and subject to be the same. Frankly, I am still confused by its mechanism and design. I may redo it with a panda.merge() based mechanism but not at this point.

Please remind me to review this with you when you are ready to work on this. I'm not sure how much we should trust the untested codes from Yin -- I would not release any libraries without unit testing.
