### ISSUE TITLE
python MOFA taking leafcutter input create duplicate rows on the output and stop peer from working

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#420]
The MOFA2 module contains a python step and a R step, where information is transfer using a hd5 file.

When the python step are done, it will save the model into the hd5 file using its own function`ent.save()`, where ent is a class governing the MOFA2 process.  However, this saving of hd5 file changes some of the leafcutter id. The number of unique ID are changed, as demonstrated below: 

```
ent.save('/mnt/vast/hpc/csg/xqtl_workflow_testing/finalizing/output/peer_debug/problem_peer.PEER_MODEL.hd5')
filename = "/mnt/vast/hpc/csg/xqtl_workflow_testing/finalizing/output/peer_debug/problem_peer.PEER_MODEL.hd5"
data1 = h5py.File(filename, "r")["features"]["view0"][()]
len(set(list(ent.data_opts["features_names"][0])))
[71]:
286467
[69]:
len(set(list(data1)))
[69]:
285779
```
This issue prevents the R step from preceding. In the entry point of its R step, there is a QC check dedicated to this duplication of ID, therefore I suspect this issue could have happened before to others.

**Comment by hsun3163** [comment]
It is likely that the issue is similar to 
https://github.com/bioFAM/MOFA2/issues/91

**Comment by hsun3163** [comment]
Indeed this issue is caused by truncation of file name.
Following are the original ID
```
'chr3:125766818:125848253:clu_64950_+:ENSG00000284624',
 'chr3:125766818:125848253:clu_64950_+:ENSG00000284660']
```
But after saving to the hd5, it became
```
chr3:125766818:125848253:clu_64950_+:ENSG000002846_view0 
```

**Comment by hsun3163** [comment]
At this point, there  are two things we can do
1. Leveraging the fact that the order are the same. At the R step we create a custom R function that load the model, added back the right id, then go through the QC
2. As we know what the problem is, I can try to modify the python code of the "ent.save()" which removes the truncation limit.

solution 1 is ugly but easy. solution 2 may involved undetermined amount of obstacle

**Comment by gaow** [comment]
I suspect that truncation happened prior to `save`. Maybe you can look into the `ent` object and see if we can fix it there? For the time being the ugly option of 1 is acceptable because it looks 13 days ago they added that to the milestone of next release. It should be fixed very soon.

**Comment by hsun3163** [comment]
I found a third solution, that is after ent save the hd5, open it again and put in the right info.  completing it now.

**Comment by hsun3163** [comment]
Fixed in the new PR

**Comment by gaow** [comment]
Alright, this looks like an ugly version of solution 2 above which is fine as a temporary solution. Let's keep it for now until they fix it later with MOFA2.
