### ISSUE TITLE
Figures in pipelines

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#44]
Currently figures are included in notebook documents as eg 

```
![Blank diagram (1).png](attachment:4e68e935-557f-4740-88cf-b289a53b1843.png)
```

this will not work when converted to HTML via `jupyter-book`, possibly a `jupyter-book` bug:

https://cumc.github.io/xqtl-pipeline/pipeline/data_preprocessing/genotype_preprocessing.html

@hsun3163 @Gou-29  can we try move all images to `images` folder in the root repo and use relative paths to that image, when you are in one of  the sub-folders under `pipeline`?

**Comment by hsun3163** [comment]
>root repo and use relative paths to that image, when you are in one of the sub-folders under pipeline
I can upload the images to images folder but I am not sure how to access those via path though

**Comment by gaow** [comment]
```
![captain](../../images/file.png)
```
