### ISSUE TITLE
SuSiE beta/se are uncorrelated with that of TensorQTL

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#445]
For gene ABCA7, with MAC =5, there are  3260 beta/se  generated by SuSiE, 1588  nominal beta/se from tensorQTL. The overlap is 1559.

Among the 1559 sumstat, the correlation of beta, se, and z scores are 
-0.0171467155186315, -0.0168848274367687, 0.00146767466225054

respectfully. 

This indicates something could be seriously wrong with the susie analysis, which in turns explains the lack of any cs.

The code used for the comparison and diagnosis will be posted later once pushed to github
repo brain-xqtl-analysis.

**Comment by gaow** [comment]
@hsun3163 I think the first thing to check is whether data is loaded correctly. Remember previously we have compared tensorQTL, APEX and SuSiE. We found decent consistency between tensorQTL and SuSiE.

**Comment by gaow** [comment]
Can we check with some interactive code for tensorQTL analyzing one gene?

**Comment by hsun3163** [comment]
As it turned out, this issue is due to covariates file being different. However, while using the "correct" covariate file. All coef from susie are 0.

**Comment by gaow** [comment]
Hmm what's special about covariate 63? What if we just adjust for that covariate? Still the primary issue is why susieR and tensorQTL give different results here when in your initial assessment of pseudo-bulk they are similar. Did you try to analyze this region also using tensorQTL?

**Comment by hsun3163** [comment]
> Hmm what's special about covariate 63? What if we just adjust for that covariate? Still the primary issue is why susieR and tensorQTL give different results here when in your initial assessment of pseudo-bulk they are similar. Did you try to analyze this region also using tensorQTL?

Yes, tensorQTL give the same result as shrishtee's

**Comment by hsun3163** [comment]
After swapping out the covariates file, the result using un-residualized X and Y also changed which should not have. The only thing this two will be impacted on is taking the intersection of samples with the covariate file.

After fixing the sample scrambling issue, the problem is fixed and the proper image can be produced.

**Comment by hsun3163** [comment]
Following shown the relationship for beta/se for the two analysis. I imagine they are the different due to how susie estimate the beta?

<img width="1416" alt="Screen Shot 2022-10-13 at 11 55 07 AM" src="https://user-images.githubusercontent.com/54919134/195678938-bf475d70-ed24-44ac-ba88-3d3246cee74f.png">

**Comment by hsun3163** [comment]
Got it, the z score are exactly identical, only differed due to having different decimal places
