### ISSUE TITLE
Duplicated chr:pos not allowed in allele_flip_qc (originally sum_stat_merger)

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#46]
At the moment, the allele_flip_qc  do not allow the presence of duplicated chr:pos, i.e. in 1 position only 1 snps is allowed. While in reality, there are quite frequently duplicate chr:pos snps in the data set.

If this feature is done on purpose, is there a way to incorporate the removal of duplicate chr:pos, so that the module can keep running? 

Otherwise, can this issue be fixed?
@changebio

**Comment by gaow** [comment]
@changebio any thoughts?

**Comment by hsun3163** [comment]
as a to provide added info on this issue:

Our current pipeline will generate duplicate chr:pos in the result due to 1 snps will may be included in 2 cis regions, as exemplified below:
```
chrom | pos | ref | alt | gene | beta | se | pval | variant_id
-- | -- | -- | -- | -- | -- | -- | -- | --

6 | 32953148 | G | A | ENSG00000233627 | 0.628610 | 0.2521800 | 0.0129887 | 6:32953148_G_A
6 | 32953148 | G | A | ENSG00000229776 | 0.628610 | 0.2521800 | 0.0129887 | 6:32953148_G_A
6 | 133162089 | G | A | ENSG00000028839 | 0.130494 | 0.0541755 | 0.0163562 | 6:133162089_G_A
6 | 133162089 | G | A | ENSG00000146411 | 0.177299 | 0.0736067 | 0.0163562 | 6:133162089_G_A
```
So we will need a way to accommodate the scenario, since this is the norminal associations, I think it is safe enough to remove 1 entry among the duplicated results.

**Comment by gaow** [comment]
In this case we might have to rename them to using gene + SNP ID as the variant ID. I am wondering if we should provide a field to the YAML file indicating how the SNP ID should be constructed. eg, 

```yaml
ID: variant_id, gene
```

so we will create the merged ID using `variant_id`_`gene` columns?

**Comment by hsun3163** [comment]
> In this case we might have to rename them to using gene + SNP ID as the variant ID. I am wondering if we should provide a field to the YAML file indicating how the SNP ID should be constructed. eg,
> 
> ```yaml
> ID: variant_id, gene
> ```
> 
> so we will create the merged ID using `variant_id`_`gene` columns?

But the number are exactly the same though. because what we report is the norminal sumstat instead of a gene level one, which gene does it go with doesnt matter

**Comment by gaow** [comment]
> But the number are exactly the same though.

that simply means gene `ENSG00000233627` and `ENSG00000229776` have the same expression level. So we should keep both. For the other "duplicate" apparently the results are not the same. in QTL analysis a test refers to a gene-snp pair. 

I'm open to other ways to keep the information but deleting them is not correct. Thanks for observing and raising the discussion!

**Comment by gaow** [comment]
@hsun3163 think of this: what if you "randomly" remove a gene that happens to be a "disease gene" and you kept the result for the non-disease gene? That is why we should not remove the "duplicate" at the face value for this case.

**Comment by changebio** [comment]
> At the moment, the allele_flip_qc do not allow the presence of duplicated chr:pos, i.e. in 1 position only 1 snps is allowed. While in reality, there are quite frequently duplicate chr:pos snps in the data set.
> 
> If this feature is done on purpose, is there a way to incorporate the removal of duplicate chr:pos, so that the module can keep running?
> 
> Otherwise, can this issue be fixed? @changebio

Sorry for the late reply. if There are different SNPs with the same car:pos, I have written a powerful and complex function to deal with. But if the case is like Hao's example, the same SNPs in QTL with different genes,  the function will consider all the combinations, which may not be a good solution. 

Would we separate SNPs first by genes? then merge SNPs in each gene?

**Comment by gaow** [comment]
@changebio even if we can do that (eg have a good interface figured out), I doubt we can manage the output -- suppose you have 20K genes. Are you going to generate 20K output files as opposed to one file? 

>  if There are different SNPs with the same car:pos, I have written a powerful and complex function to deal with. 

Did you document exactly the different scenarios and how you deal with them? If not, please document in the workflow notebook

**Comment by changebio** [comment]
> @changebio even if we can do that (eg have a good interface figured out), I doubt we can manage the output -- suppose you have 20K genes. Are you going to generate 20K output files as opposed to one file?
> 
> > if There are different SNPs with the same car:pos, I have written a powerful and complex function to deal with.
> 
> Did you document exactly the different scenarios and how you deal with them? If not, please document in the workflow notebook

the function has not been used in the pipeline. I think we discussed the specific usage case in the pipeline. In the pipeline, we will only deal with the unique chr:pos. Of course, we can remove the depulicated chr:pos SNPs.

**Comment by gaow** [comment]
For our fine-mapping purpose 2+ allele SNPs and indels are typically rare and can safely be ignored. As a general purpose data merger pipeline that results in a single summary stat file in VCF format, this has to be dealt with. 

The issue with QTL that @hsun3163 has brought up is something I overlooked earlier. At this point perhaps let's deal with all these "duplicates" scenarios. We cannot simply remove them. @changebio could you think over the interface i proposed yesterday and give it a go?

**Comment by changebio** [comment]
> In this case we might have to rename them to using gene + SNP ID as the variant ID. I am wondering if we should provide a field to the YAML file indicating how the SNP ID should be constructed. eg,
> 
> ```yaml
> ID: variant_id, gene
> ```
> 
> so we will create the merged ID using `variant_id`_`gene` columns?

Do you mean this interface? rename SNPs' ID by variant_id+gene name? @gaow

**Comment by gaow** [comment]
@changebio yes this is a proposed solution. You are welcome to suggest alternatives and we can decide which ones are most reasonable to implement.

**Comment by changebio** [comment]
> @changebio even if we can do that (eg have a good interface figured out), I doubt we can manage the output -- suppose you have 20K genes. Are you going to generate 20K output files as opposed to one file?
> 
> > if There are different SNPs with the same car:pos, I have written a powerful and complex function to deal with.
> 
> Did you document exactly the different scenarios and how you deal with them? If not, please document in the workflow notebook

We don't need to write the sumstats gene by gene. We can do the sumstats merging gene by gene. So the same SNPs in different gene can by handle properly.

**Comment by changebio** [comment]
> @changebio yes this is a proposed solution. You are welcome to suggest alternatives and we can decide which ones are most reasonable to implement.

I agree. The solution I expressed above is kind of the same. Then we need a gene column in sumstats file.

**Comment by gaow** [comment]
> We don't need to write the sumstats gene by gene. We can do the sumstats merging gene by gene. So the same SNPs in different gene can by handle properly.

I'm talking about writing the output. How is the output going to look like, after you merge data gene by gene? You'll still end up having obviously duplicated variant ID in a VCF file that you have no way to distinguish between those variants, right? If we have to solve the variant ID issue anyways, then it might be a good idea to forget about the notion of "gene" and focus on defining what a 'variant' is; then use that for summary stats merging -- this is what I was suggesting. 

>  Then we need a gene column in sumstats file.

It can be of any column name, and will be used to define vairants. It can even be multiple columns,

```
ID: variant_id, some_col, another_col
```

or no extra column,

```
ID: variant_id
```

Or, false it to be eg:

```
ID: chr, pos
```

if you can now rethink of the problem as variant ID oriented where variant ID are to be defined by us ... Once the variant Id is defined, we'll report duplicate variant ID and keep only one of them -- reporting duplicates is important for analysts to notice and handle them.

**Comment by changebio** [comment]
"if you can now rethink of the problem as variant ID oriented where variant ID are to be defined by us ... Once the variant Id is defined, we'll report duplicate variant ID and keep only one of them"

This is a good idea. These will be easy to deal with. The first step will be finding overlapped IDs. Then remove duplicated ID and deal with flip sign.

**Comment by gaow** [comment]
@changebio I believe all we have discussed here have been implemented? The last comment/request is that for the minimal working example, should we use 

```yaml
ID: chr, pos, a0, a1
```

to explicitly encourage that default is based on these four values, and not just chr and position?

**Comment by hsun3163** [comment]
This is fixed
