### ISSUE TITLE
Issue on Projection of related individuals phase

### ISSUE THREAD

**Issue by frarosamilia** [cumc/xqtl-pipeline#464]
I am trying to perform the projection of related individual phase but I got this error: 

`
```
_`Error in quantile.default(pc$mahal, probs = prob): missing values and NaN's not allowed if 'na.rm' is FALSE
Traceback:

1. calc_mahalanobis_dist(dat$pc_scores, dat$pc_median, dat$pc_cov, 
 .     name = dat$meta)   # at line 14 of file <text>
2. quantile(pc$mahal, probs = prob)   # at line 8 of file <text>
3. quantile.default(pc$mahal, probs = prob)
4. stop("missing values and NaN's not allowed if 'na.rm' is FALSE")`_
`
```

I tried to run things interactively and seems I have the pc_scores with a lot of NAs in the PCs greater than 2, even since I settled the maha-k and the --k as 2. 
<img width="816" alt="Screenshot 2022-10-31 at 12 11 40" src="https://user-images.githubusercontent.com/79653686/199086992-cb8e357c-193e-4e45-880b-95b96c9aff2c.png">

the weird thing is that the same process, with the same parameters worked fine in a different cohort of patients. 
BUT if I tried to run step by step the R process for projecting samples for the cohort of patients that worked fine, I get a different error: 
```
`Error in UseMethod("select"): no applicable method for 'select' applied to an object of class "NULL"
Traceback:

1. calc_mahalanobis_dist(dat$pc_scores, dat$pc_median, dat$pc_cov, 
 .     name = dat$meta)   # at line 33 of file <text>
2. x %>% select("IID", "FID", "pop", starts_with("PC"))   # at line 3-4 of file <text>
3. select(., "IID", "FID", "pop", starts_with("PC"))`

Let me know for other details and If I can help in any ways
```

**Comment by hsun3163** [comment]
A key player related to the first issue is that the k is set to 2 when generating the pca, but we should see how we can accommodate such low pcs nonetheless.

a potential cause of the second issue is version of software. I think if u run it within the container it should not give u this error.

**Comment by frarosamilia** [comment]
for the second error, that could be for sure the reason why all worked smoothly and I got the error when I ran step by step without the container

**Comment by frarosamilia** [comment]
Ok, the problem was solved when I tried to re run all the pipeline again, 
that seems some k inconsistency problem maybe due to some cache.
