### ISSUE TITLE
Summary statistics merger allow unique variants

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#54]
@changebio one missing step for summary stats merge pipeline is to create the merged data in VCF format, which @hsun3163 can help with later. Currently I wonder if our appoarch of dealing with unique variants (by removing them) is the best thing to do, particularly when you consider many data-sets merged. For example if we merge 10 files and 9 out of the 10 files has a variant, but the 10th does not have it. Currently, this variant will be removed. But alternatively, it can also be kept and we should use the missing data convention in VCF file to keep it? I believe with VCF manipulation software it should be easy to select variants that appears in all data-sets. Therefore I dont see an issue keeping all variants in the VCF output even if they present only in one file.

**Comment by changebio** [comment]
The pipeline only write out the common SNPs in all the files.

If we want to write out all SNPs which match with target file (the union SNPs of each file matching with target file), I can modify the pipeline to do that.

**Comment by gaow** [comment]
Thanks @changebio yes we need to implement this.

I'm wondering what if we dont have a specific "target" file, or there are multiple choices of target file. For example consider eQTL analysis for different tissues of the same individuals. Each tissue is a phenotype. There is no particular target to merge them with. However each tissue may have its own subset of individuals (some donors are collected for only certain tissues), thus results in potentially unique variants in each of the tissues. When we try to match it with a particular target tissue (randomly picked) this will end up dropping some data.

my current thought is that we can allow for the "target data" input to be as minimal as simply `chr, pos, a0, a1`. In that case, we can create such a file direclty from, eg, the original genotype data; or even use things like dbSNP genotype, or whatever matches the genotype information that the LD is computed from. This will solve the issue for the QTL application as I outlined above.

**Comment by changebio** [comment]
"my current thought is that we can allow for the "target data" input to be as minimal as simply chr, pos, a0, a1. "

Yes. The target file can be a file only with chr,pos,a0 and a1 columns, or a sumstats with these columns.
