### ISSUE TITLE
TensorQTL - trans error

### ISSUE THREAD

**Issue by m-mews** [cumc/xqtl-pipeline#548]
I'm trying to run the trans analysis using the TensorQTL.ipynb, but I'm receiving the below error. Any thoughts? Thank you in advance!

sos run xqtl-pipeline/code/association_scan/TensorQTL/TensorQTL.ipynb trans \
   --genotype-file nhw_239/geno/geno_final/nhw_chr_1_22.no_rel.filtered.bed \
   --phenotype-file nhw_239/mol_phe/nhw_gene_tpm_prep_v2.low_expression_filtered.outlier_removed.tmm.expression.bed.gz \
   --covariate-file nhw_239/cov/nhw_no_rel.rnaseqc.low_expression_filtered.outlier_removed.tmm.expression.cov_pca.resid.PEER.cov.gz  \
   --cwd nhw_239/tensorqtl/trans  \
   --name nhw_no_rel \
   --MAC 5 \
   --region-list ad_trans_gene_regions.tsv \
   --region-name gene_id \
   --container xqtl-pipeline/container/singularity/TensorQTL.sif

INFO: Running trans_1: 
ERROR: trans_1 (id=6f075eae72e9a68e) returns an error.
ERROR: [trans_1]: [0]: Executing script in Singularity returns an error (exitcode=1, stderr=/mnt/pan/Data14/metabrain_lasso/rna_seq_norm/nhw_239/tensorqtl/trans/nhw_gene_tpm_prep_v2.low_expression_filtered.outlier_removed.tmm.expression.norminal.trans_long_table.txt.stderr, stdout=/mnt/pan/Data14/metabrain_lasso/rna_seq_norm/nhw_239/tensorqtl/trans/nhw_gene_tpm_prep_v2.low_expression_filtered.outlier_removed.tmm.expression.norminal.trans_long_table.txt.stdout).
The script has been saved to /home/mxm1368/.sos/19d2b6ee7290e278//home/mxm1368/.sos/19d2b6ee7290e278.To reproduce the error please run:
singularity exec  xqtl-pipeline/container/singularity/TensorQTL.sif python /home/mxm1368/.sos/19d2b6ee7290e278/singularity_run_12632.py
[trans]: Exits with 1 pending step (trans_2)

singularity exec  xqtl-pipeline/container/singularity/TensorQTL.sif python /home/mxm1368/.sos/19d2b6ee7290e278/singularity_run_12632.py
Warning: 'rfunc' cannot be imported. R and the 'rpy2' Python package are needed.
Mapping files: 100%|██████████████████████████████| 3/3 [01:30<00:00, 30.18s/it]
trans-QTL mapping
  * 236 samples
  * 82 phenotypes
  * 44 covariates
  * 67510012 variants
    processing batch 6752/6752
    elapsed time: 0.80 min
  * 9939322 variants passed MAF >= 0.01 filtering
done.
trans-QTL mapping (permutations)
  * 236 samples
  * 44 covariates
  * 67510012 variants
    processing batch 6752/6752
Traceback (most recent call last):
  File "/home/mxm1368/.sos/19d2b6ee7290e278/singularity_run_12632.py", line 33, in <module>
    perm_df = trans.map_permutations(genotype_df, covariates_df, batch_size=10000,
  File "/opt/conda/lib/python3.8/site-packages/tensorqtl/trans.py", line 408, in map_permutations
    m,_ = r2_t.max(0)
IndexError: max(): Expected reduction dim 0 to have non-zero size.

**Comment by gaow** [comment]
@m-mews we cannot reproduce it on our end, and we actually don't need permutation testing in our current pipeline using fine-mapping to follow up on marginal assocaitions. I will close the ticket for now. We will release more detailed trans workflow recommendation when i get a chance to document that with inputs from @grennfp . Thanks for your patience!
