### ISSUE TITLE
1 sample short after GWAS QC.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#58]
after running GWAS qc on all the ROSMAP data, it occurs that there is 1 sample short for the genotype of chr 4 , but not other chromosome. 

This is due to the mind setting in GWAS_QC 1.

To allow for smooth run in downstream analysis, two option is available 
1. remove the mechanism to remove samples base on missingness
2. remove the samples from all the chromosome using added mechanism.

For the time being, option 1 was taken

**Comment by gaow** [comment]
Sample level QC should always be performed with all variants. Option 1 is the right thing to do and option 2 is wrong. However with option 1, we will not have a mechanism to globally QC at the sample level. Don't we perform QC before splitting data by chrom? That is the only right thing to do. We need all chroms for genotype level PCA anyways. Can we perform QC with all chroms combined?

**Comment by hsun3163** [comment]
> Sample level QC should always be performed with all variants. Option 1 is the right thing to do and option 2 is wrong. However with option 1, we will not have a mechanism to globally QC at the sample level. Don't we perform QC before splitting data by chrom? That is the only right thing to do. We need all chroms for genotype level PCA anyways. Can we perform QC with all chroms combined?

The original gwas QC was done on the per chorm plink bc that is what our input was. To do option 1 I guess we can switch the order in gwas QC module

**Comment by gaow** [comment]
Yes we must switch the order and perform this upfront. With newer version of PLINK it can possibly support other formats such as bgen. But for common variant QTL analysis, extracting them from VCF or bgen and QC them before splitting to different chroms is the best approach.

**Comment by hsun3163** [comment]
> Yes we must switch the order and perform this upfront. With newer version of PLINK it can possibly support other formats such as bgen. But for common variant QTL analysis, extracting them from VCF or bgen and QC them before splitting to different chroms is the best approach. 

On it

**Comment by hsun3163** [comment]
Changes implemented
