### ISSUE TITLE
Error when running VCF_QC under new container

### ISSUE THREAD

**Issue by zq2209** [cumc/xqtl-pipeline#611]
Hello，
When I am using our `VCF_QC` to run `qc` on genotype VCF files by using the new container, there was an error message: `critical libmamba [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal`. 

This error occurred when running `qc_1`. 

```bash
bash: container = container, expand= "${ }", stderr = f'{_output:n}.stderr', stdout = f'{_output:n}.stdout', entrypoint=entrypoint
    # split multiallelic sites into biallelic records 
    ${'bcftools norm -m-any' if not bi_allelic else 'bcftools view -m2 -M2'} ${'-v snps' if snp_only else ""} ${_input} |\
    # Fix incorrect or missing REF alleles and warn about them
    bcftools norm -d exact -N --check-ref ws -f "${reference_genome}" -Oz --threads "${numThreads}" |\
    # Fill missing tags
    bcftools +fill-tags -- -t all,F_MISSING,'VD=sum(FMT/DP)' | \
    # Remove ID and replace with CHROM:POS:REF:ALT format
    bcftools annotate -x ID -I +'%CHROM:%POS:%REF:%ALT' | \
    # Annotate with dbSNP rsID
    bcftools annotate -a ${dbsnp_variants}  -h <(echo '##INFO=<ID=RSID,Number=1,Type=String,Description="dbSNP rsID">') \
        -c CHROM,FROM,TO,INFO/RSID -Oz --threads ${numThreads} -o ${_output}

bash: expand= "${ }", stderr = f'{_output:n}.stderr', stdout = f'{_output:n}.stdout', container = container, entrypoint=entrypoint
    for i in ${_output} ; do 
        # Capture file metadata
        output_info="$i"
        output_size=$(ls -lh "$i" | awk '{print $5}')
        output_rows=$(zcat "$i" | wc -l)
        output_column=$(zcat "$i" | grep -v "##" | head -1 | wc -w)
        output_header_row=$(zcat "$i" | grep "##" | wc -l)
        output_preview=$(zcat "$i" | grep -v "##" | head | cut -f 1-11)

        # Write captured information to the stdout file
        printf "output_info: %s\noutput_size: %s\noutput_rows: %d\noutput_column: %d\noutput_header_row: %d\noutput_preview:\n%s\n" \
            "$output_info" "$output_size" "$output_rows" "$output_column" "$output_header_row" "$output_preview" >> ${_output:n}.stdout
    done
```

And there are 22 VCF files to run in total, only 2 VCF files occurred this problem. Other 22 files worked fine. 

Here are something that confusing me:
1. I have tried the same pipeline but using the old container that we have, everything is working fine now, even for those two that not worked under new container. So, I basically don't think there is something wrong with the input files. 
2. The commands in `qc_1` are `bcftool`, so I am wondering why there is a `json error`. 

Are there any thoughts on this error?

**Comment by zq2209** [comment]
Follow up on this issue. I met this error again when I was running `plink_by_chrom`. Basically it is using Plink to partition entire genotype by chromosome. Commands shown below:
```
[plink_by_chrom_1]
stop_if(len(paths(genoFile))>1, msg = "This workflow expects one input genotype file.")
parameter: chrom = list
input: genoFile, for_each = "chrom"
output: f'{cwd}/{_input:bn}.{_chrom}.bed'
# look up for genotype file
task: trunk_workers = 1, trunk_size = job_size, walltime = walltime, mem = mem, cores = numThreads, tags = f'{step_name}_{_output:bn}'
bash: expand= "$[ ]", stderr = f'{_output}.stderr', stdout = f'{_output}.stdout', container = container, volumes = [f'{genoFile:ad}:{genoFile:ad}'], entrypoint=entrypoint
    ##### Get the locus genotypes for $[_chrom]
    plink --bfile $[_input:an] \
    --make-bed \
    --out $[_output[0]:n] \
    --chr $[_chrom] \
    --allow-no-sex  --keep-allele-order || true 
```
This error showed in `stderr` file:
```
cat ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed.stderr
critical libmamba [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

But the true reason for this job failed was mem issue. Here is the error message in corresponding log file
```
cat ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.1.bed.stderr
Error: Out of memory.  The --memory flag may be helpful.
Failed allocation size: 1554992768
```
After I requested more mem, everything went well. 

So I basically think there is also another error, such as memory issue, that causes `vcf_qc` failed. But this error message is quite miss leading. People can't get an exact error message.

**Comment by danielnachun** [comment]
Thanks for digging more into this - I think the solution here might be to add `--no-capture-output` to the entry point argument.  So the entry point command would be `micromamba run --no-capture-output -n bioinfo`.  Can you see if that allows the user to see the error?

**Comment by gaow** [comment]
Thanks @danielnachun !! am adding those `--no-capture-output` now to pipelines. I'll reopen if we stil lhave a problem.

**Comment by zq2209** [comment]
@danielnachun A new issue occurred after we added `--no-capture-output` to the entry point parameter, like this `entrypoint=('micromamba run --no-capture-output -n' + ' ' + container.split('/')[-1][:-4]) if container.endswith('.sif') else ""`

If this modification is correct, then we met a new issue after adding this. Here is the error message:
```
cat ROSMAP_NIA_WGS.leftnorm.bcftools_qc.plink_qc.pQTL.kin0.stderr
/tmp/6103969.1.csg.q/mambafKSsedVd8lx: line 5: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [argument ...]] [redirection ...]
```
This is to run our GWAS_QC pipeline, using `kingship` to detect related individuals. But after we remove `--no-capture-output`, everything went well.

**Comment by danielnachun** [comment]
We've resolved this issue now, the root cause was that `--no-capture-output` is for `conda`/`mamba`, and the equivalent command for `micromamba` is actually `-a ""`, which tells `micromamba` not to "attach" any of the outputs and just print them out immediately.
