### ISSUE TITLE
New errors in flashpca after using new GWAS_QC order

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#62]
Following errors pop up in the new PCA run with the merged then QC genotypes. 

```
Error in project(frel, loadings = f$loadings[overlapped_variants, ], orig_mean = f$center[overlapped_variants],  :
  orig_sd cannot be zero or negative
```

This error occurs in the project_sample step of the pca modules in this line:
```
fpro <- project(frel, loadings=f$loadings[overlapped_variants,], orig_mean=f$center[overlapped_variants], orig_sd=f$scale[overlapped_variants], ref_allele=ref)
```
where f is the pca_model generated in the previous step
As it turns out there are quite a bit of orig_sd = 0 in all three samples.
Am trying different sets of parameter to make this issue disappear

**Comment by gaow** [comment]
Are they monomorphic sites that should have been removed?

**Comment by hsun3163** [comment]
No, I have looked at some of the sd of the problemetic variants. In both the overall datas and the unrelated_sample data (the one that are actually fed into pca for pca_model). The MAF is low(0.03~0.09), but not zero.

**Comment by gaow** [comment]
So these are indeed "common" variants (MAF>0.01)? I'm pretty sure that scale stands for the standard deviation used in standardizing the X matrix. Actually I now find it [here](https://github.com/gabraham/flashpca/blob/b8044f13607a072125828547684fde8b081d6191/flashpcaR/R/scale2.R#L28) i believe this is what they did.

**Comment by hsun3163** [comment]
Yes I have tried and found that the sd of the scaled X matrix is still normal.

But nvm, I figured out the problem, it is in fact happened not within module but a problem within the input.
