### ISSUE TITLE
Unify singularity and docker configuration files

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#67]
As a good engineering practice please move all container configuration to using docker and we'll run the following command to automatically generate singularity configurations:

```
# pip3 install spython
spython recipe Dockerfile &> Singularity.def
```

**Comment by hsun3163** [comment]
Dockerfile can be automatically generated from singularity recipe now.
This is done via the same commands:

`spython recipe singularityfile dockerfile --parser singularity`

However one caveat for this method is that, it cant be used directly on the singularity file that are generated from spython.
The stage:spython-base statement will produce some errors. Renaming the stage or deleting this line altogether can solve this issue.

**Comment by gaow** [comment]
Thanks i'll see for myself and handle that `stage:spython-base` . What is this `stage`? something like a tag in docker? I want to rename it to something meaningful for each recipe, but do this automatically. What do you suggest?

**Comment by hsun3163** [comment]
> Thanks i'll see for myself and handle that `stage:spython-base` . What is this `stage`? something like a tag in docker? I want to rename it to something meaningful for each recipe, but do this automatically. What do you suggest?

According to https://sylabs.io/guides/3.2/user-guide/definition_files.html#multi-stage-builds , I think it is a collection of enviorment. which without specific meaning in our 1 stage build.
