### ISSUE TITLE
Data QC for RNA-seq

### ISSUE THREAD

**Issue by gaow** [cumc/xqtl-pipeline#68]
@Gou-29 asked me earlier about RNA-seq QC and data preprocessing. The answer for now is that we stick to what GTEx has done by using their code. However I think this paper is a very useful reference if you want to understand more details:

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04307-0

**Comment by gaow** [comment]
We have currently implemented RNA-seq calling from fastq to counts (thanks @Gou-29 ). There are some additional optional QC procedures in the dash box in the paper above, that might be a good idea to check out and implement down the road. I believe this is what those authors have:

https://github.com/stormlovetao/eQTLQC/blob/master/Sample/src/report.Rmd

we need to streamline this. @hsun3163 I'm documenting it here for now and I'll follow up with you later on making a separate module for it.

**Comment by hsun3163** [comment]
So am I correct that essentially the scope of our pipeline of this part is like 

Raw read -> {Quantification }-> Count and TPM table -> {QC on count} -> {Normalization} -> bed -> {Other Data Processing stage}

**Comment by hsun3163** [comment]
> We have currently implemented RNA-seq calling from fastq to counts (thanks @Gou-29 ). There are some additional optional QC procedures in the dash box in the paper above, that might be a good idea to check out and implement down the road. I believe this is what those authors have:
> 
> https://github.com/stormlovetao/eQTLQC/blob/master/Sample/src/report.Rmd
> 
> we need to streamline this. @hsun3163 I'm documenting it here for now and I'll follow up with you later on making a separate module for it.

Do we need to rewritten the codes or can we reused those as long as it run?

**Comment by gaow** [comment]
> Do we need to rewritten the codes or can we reused those as long as it run?

Reuse but make them into pipelines. Currently they are interactive analysis codes.

> Raw read -> {Quantification }-> Count and TPM table 

already done by @Gou-29 

> Normalization} -> bed -> {Other Data Processing stage}

We already have it.

what's missing is just ` -> {QC on count} -` module which is what that Rmd file is about I believe. We can discuss that later.

**Comment by hsun3163** [comment]
The QC on count module was actually by itself streamlined and I just figure out how that works:
```
It use a python wrapper to kick start the rmd file to generate a html QC report and 1 qced tpm table based on a JSON config file.
```

The whole thing is quite self-contained. So, I am inclined to use sos to just generate the config and let their rmd file to read the config automatically. And then another step to changes the readcounts table consistant with this tpm output.

So Ideally it would be an three step module that governed by following commands.

```
nohup sos run readcounts_QC qc --countTMP {filename} --wd {path} --container {sif}  & 
```
___
Alternatively, I can also changes how the rmd works and get rid of the config file, which may take more time to do and debug. (edited)

**Comment by hsun3163** [comment]
Done
