### ISSUE TITLE
Should we use covariate + factor again for association scan?

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#70]
while making this:
I realized the factor and covariate we estimated is infact taken into considerations twice.
1. in remove_covariate
2. internally in APEX/TensorQTL
![xqtlflowchart - Page 1](https://user-images.githubusercontent.com/54919134/148148509-46bd1f7c-e563-4c8b-8ed7-c4c80d7b74df.png)

So should we input the covariate again into the APEX/TensorQTL module ?

**Comment by gaow** [comment]
remove covariate is an optional step when we want to do fine-mapping with full data (and not summary stats). This usually perform better than fine-mapping with summary stats as we've shown in SuSiE and SuSiE RSS papers. We should use original phenotype and covariates for tensorQTL and APEX.

**Comment by hsun3163** [comment]
Got it
