### ISSUE TITLE
Inconsistency between the example and workflow code

### ISSUE THREAD

**Issue by mw201608** [cumc/xqtl-pipeline#717]
For "Phenotype partition by chrom" https://cumc.github.io/xqtl-pipeline/code/data_preprocessing/phenotype_preprocessing.html), the example calls partition_by_chrom, but the actual work flow names phenotype_by_chrom.

**Comment by gaow** [comment]
Sorry @mw201608 for some reason this page  https://cumc.github.io/xqtl-pipeline/code/data_preprocessing/phenotype_preprocessing.html is not updated ... it is supposed to be the HTML version of https://github.com/cumc/xqtl-pipeline/blob/main/code/data_preprocessing/phenotype_preprocessing.ipynb but for some reason, the HTML file did not render.

Until we fix that, could you please go by the `ipynb` files?
