### ISSUE TITLE
Python not found rna_quantification container

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#784]
While trying to run code (form the `reference_data_preparation.ipynb` notebook), I run into an issue where `python` isn't found in the `rna_quantification` container. I was wondering if anyone ran into this or if this may be a local problem on my end.

**Comment by gaow** [comment]
@Travyse what software container are you using? You need to update to our latest version. eg `singularity pull ghcr.io/cumc/rna_quantification_apptainer:latest`. In fact if you update SoS software to version 0.24.3 you should be able to do it automatically: `--container ghcr.io/cumc/rna_quantification_apptainer:latest`

**Comment by Travyse** [comment]
I did update to the latest version of the container, but I haven't updated sos to do it automatically. I can maybe try creating a new environment to make things a bit cleaner.

**Comment by gaow** [comment]
@Travyse if your SoS is < 0.24.1 then I do expect you run into the issue you describe even if you manually updated your image.

**Comment by Travyse** [comment]
@gaow That was indeed the issue, thanks
