### ISSUE TITLE
RNA_calling.ipynb rnaseqc_call stalls

### ISSUE THREAD

**Issue by Travyse** [cumc/xqtl-pipeline#791]
I'm running `rnaseqc_call` on a dataset and it never appears to complete. Upon running the command initially, the jobs are verifiably submitted to the job queue. The jobs do run for some time in the queue, from what I can see. The jobs then are removed from the queue after some time, but there is no change in job status on SOS's end (neither a failure nor a success). In addition, there are no changes to any output files in the target directory. Typically SOS continues reporting job information (waiting for XXX jobs to complete before submitting more to the queue) until it crashes. I've pasted the command used.

```
    nohup sos run xqtl-pipeline/12-28-2023/pipeline/RNA_calling.ipynb rnaseqc_call \
    --cwd output/star_output \
    --samples data/phenotype/STARNET_ribo0_fastq.filename_only.trimmed.txt \
    --data-dir output/trimmed_fastqs \
    --STAR-index reference_data/STAR_Index/ \
    --gtf reference_data/Homo_sapiens.GRCh38.103.chr.reformatted.gene.ERCC.gtf \
    --container containers/rna_quantification_apptainer:latest.sif \
    --reference-fasta reference_data/GRCh38_full_analysis_set_plus_decoy_hla.noALT_noHLA_noDecoy_ERCC.fasta \
    --ref-flat reference_data/Homo_sapiens.GRCh38.103.chr.reformatted.ERCC.ref.flat \
    --bam_list /output/star_output/STARNET_ribo0_fastq.filename_only.trimmed_bam_list \
    -s build  -c config.yml  -q lfs > rnaseqc_call.out
```

**Comment by gaow** [comment]
@Travyse not sure how reliably we can reproduce this ... what happens if you resubmit to rerun?

**Comment by gaow** [comment]
@Travyse looks this is resolved since you've past this step for your dataset -- what was the solution?

**Comment by Travyse** [comment]
The issue had to do with my environment. For some reason, loading `glibc` to the environment caused segmentation faults for all of the jobs before they had a chance to run. The solution was to just stop loading this library.
