### ISSUE TITLE
polyfun container issue 

### ISSUE THREAD

**Issue by at-crx** [cumc/xqtl-pipeline#82]
polyfun notebook step 3 method 1 (using extract_snpvar.py) encounters an error when the input sumstats file is in `.txt.gz` format. The error does not occur when the packages for the container are installed in a cluster directory and the command is run from there. 

Original error when run using container 
![image](https://user-images.githubusercontent.com/42452275/149542005-871f0116-b966-492e-bbf8-cabf6f85c53e.png)

**Comment by hsun3163** [comment]
>The error does not occur when the packages for the container are installed in a cluster directory and the command is run from there.

Via running the sos without the container. It is verified that the issue of unable to read txt.gz sumstat is caused by the container. However, it is uncleared what exactly cause the issue. The next step of figuring this out is to look into the actual script to see what went wrong.

**Comment by hsun3163** [comment]
As it turn out. The problem only exist when running the sos code on a computational node, without using the task system, i.e. 
```
nohup sos run ...  &
```
Both running in the login node and running with the `-J 200 -q csg -c /home/hs3163/GIT/ADSPFG-xQTL/code/csg.yml` option can complete the run successfully.
 
It is likely that, the recorded exception 
```
OSError: Could not open parquet input source '<Buffer>': Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
```
is not the true cause of failure, but the
```
/mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/tmpowd2ig85/singularity_run_10965.sh: line 4: 11009 Aborted                 (core dumped) python /usr/local/bin//extract_snpvar.py --sumstats /mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/demo.sumstats_munged.parquet --out /mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/demo.pcp.gz --allow-missing
/mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/tmpltwqwpnk/singularity_run_35733.sh: line 4: 35776 Segmentation fault      (core dumped) python /usr/local/bin//extract_snpvar.py --sumstats /home/at3535/polyfun/AD_sumstats_Jansenetal_2019sept.txt.gz --out /mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/demo.pcp.gz --allow-missing
python: can't open file '/usr/local/bin//extract_snpvar.py': [Errno 2] No such file or directory
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/tmpbx99yj93/singularity_run_26261.sh: line 4: 26305 Aborted                 (core dumped) python /usr/local/bin//extract_snpvar.py --sumstats sumstat_demo.gz --out /mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/demo.pcp.gz --allow-missing
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/tmp_w3vnf7i/singularity_run_26339.sh: line 4: 26383 Aborted                 (core dumped) python /usr/local/bin//extract_snpvar.py --sumstats sumstat_demo.gz --out /mnt/mfs/statgen/xqtl_workflow_testing/demo/polyfun/demo.pcp.gz --allow-missing
```

The take home message is to run the module with the task option on, and the container is fine.
