### ISSUE TITLE
singularity build cancelled due to unavailable arch (amd64)

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#86]
While using 
`singularity build --remote apex.sif apex.def`
following error occurs:
```
build (61e87324257059d3222630cc) cancelled due to unavailable arch (amd64)
FATAL:   While performing build: build image size <= 0
```
This error happened to all but one def file, whose content is merely:
```
Bootstrap: docker
From: gaow/base-notebook
```
which ran successfully

**Comment by hsun3163** [comment]
After the completion of the building of aforementioned def. and running 
`qlogin -q csg.q `  + logout of the computational node.

The error disappeared. 

This is a log for what happened in case this error popup again.

**Comment by gaow** [comment]
Thanks @hsun3163 I suggest against using remote build anyways. I changed instruction on `container/singularity/README.md`

**Comment by hsun3163** [comment]
> Thanks @hsun3163 I suggest against using remote build anyways. I changed instruction on `container/singularity/README.md`

This problem happened again. None of what I done earlier can fix it (as expected). Will talk to the syslab ppl on slack later regarding this issue.

**Comment by hsun3163** [comment]
The syslab ppl said they fix the problem, will update when new problem arise
