### ISSUE TITLE
Moving STAR_indexing & RSEM_indexing to a new module.

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#96]
At the moment, the optional step of generating index for STAR and RSEM are includes as the part of the bulk_expression module, and they really dont share any input with the rest of the steps. Perhaps these two steps shall, along with the collapse gene model for gtf, be put into an optional module that call something like "refernce_processing" prior to the bulk_expression module.

**Comment by gaow** [comment]
Agreed. We should also move there the gff convertion and gene model collapsing.

**Comment by hsun3163** [comment]
done and testing

**Comment by hsun3163** [comment]
testing done
