### ISSUE TITLE
Additional software needed in docker

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#97]
- [x] 1. trimmomatic-0.39.jar in rna_quant
- [x] 2. collapse_annotation.py script in bioinfo
- [x] 3. gffread in bioinfo
- [x] 4. Normalization script in bioinfo

**Comment by hsun3163** [comment]
- [ ]

**Comment by gaow** [comment]
>  2. collapse_annotation.py script in bioinfo

This should go to `rna_quant`

**Comment by gaow** [comment]
I fixed it.
