### ISSUE TITLE
Error while running remove adaptor on computational node

### ISSUE THREAD

**Issue by hsun3163** [cumc/xqtl-pipeline#99]
while running 
```
sos run /home/hs3163/GIT/xqtl-pipeline/pipeline/molecular_phenotypes/bulk_expression.ipynb Remove_adaptor \
    --fastq1_raw data/samp1_r1.fq.gz \
    --fastq2_raw data/samp1_r2.fq.gz \
    --soft_dir data/Trimmomatic-0.39/ \
    --sample_id samp1 
```
On computational node.

following error occurs

```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

However, while running the same command in login node, it ran successfully.

**Comment by hsun3163** [comment]
The step of PicardQC also didnt run on out computational node

**Comment by gaow** [comment]
If there is a memory issue you should make the java command memory setting to be consistent with the `mem` global option (or slightly smaller than the specified `mem`

**Comment by hsun3163** [comment]
> If there is a memory issue you should make the java command memory setting to be consistent with the `mem` global option (or slightly smaller than the specified `mem`

As it turn out, this is not a mem issue, in the picard (mark duplicate) step, the specify mem for the Java statement is 3G, which is way smaller than the mem parameter.

**Comment by hsun3163** [comment]
As it turn out, the java probelm is many fold:
1. When the java running encountered some error, i.e. use --version instead of -version, it will quit with 
```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

2. After qlogin, if h_vem is not significantly (at least 3GB) larger than requested mem,  it will quit with error message:
```
hs3163@node57:/mnt/mfs/statgen/xqtl_workflow_testing/rna_quant$ cd ~
hs3163@node57:~$ java
Error occurred during initialization of VM
Unable to setup metadata virtual space list.
```

3. The problem where --mem 16G but still fail to create VM could be a problem with the task statement initially introduced to avoid the problem, or it could be due to some parameter embedded within the GTEX wrapper.

Therefore:
1. This problem should not occurs with the java command being invoked directly 
2. `java_mem` needs to be at least 3GB smaller than `mem`
3. If run without `-J -c -q` , the `qlogin` command needs to be accompanied by `-l --h_vmem=6G` 

____________________________________________
This problem should be fixed, and will close until a new problem emerges.
